#include <stdint.h>
#include <unistd.h>
#include <stddef.h>

/* Linker-script symbols (kernel.ld) */
uint64_t _kernel_start = 0x00100000;
uint64_t _stack_top = 0x00200000;
uint64_t _image_start = 0x00100000;
uint64_t _bss_start = 0x001F0000;
uint64_t _bss_end = 0x001FC000;
uint64_t _text_end = 0x001F0000;

/* Self-test runner */
int wubu_self_test_run(const char *name) { (void)name; return 0; }

/* Globals from excluded modules (arch/tasking) */
uint64_t task_tick_count = 0;

/* Auto-generated stubs for functions called by
 * selftests but not defined in any kernel .c file. */
void wubu_accel(void) {}  /* TODO: implement */
void wubu_adreno600(void) {}  /* TODO: implement */
void wubu_adreno700(void) {}  /* TODO: implement */
void wubu_aec(void) {}  /* TODO: implement */
void wubu_ampere(void) {}  /* TODO: implement */
void wubu_arctic_islands(void) {}  /* TODO: implement */
void wubu_audio(void) {}  /* TODO: implement */
void wubu_audiofw(void) {}  /* TODO: implement */
void wubu_auracast(void) {}  /* TODO: implement */
void wubu_backlight(void) {}  /* TODO: implement */
void wubu_backlightpwm(void) {}  /* TODO: implement */
void wubu_bap(void) {}  /* TODO: implement */
void wubu_bcache(void) {}  /* TODO: implement */
void wubu_bio(void) {}  /* TODO: implement */
void wubu_blkqos(void) {}  /* TODO: implement */
void wubu_bt(void) {}  /* TODO: implement */
void wubu_bta2dp(void) {}  /* TODO: implement */
void wubu_btamesh(void) {}  /* TODO: implement */
void wubu_btaudio(void) {}  /* TODO: implement */
void wubu_btbeacon(void) {}  /* TODO: implement */
void wubu_btclassic(void) {}  /* TODO: implement */
void wubu_bthfp(void) {}  /* TODO: implement */
void wubu_bus(void) {}  /* TODO: implement */
void wubu_calib(void) {}  /* TODO: implement */
void wubu_camera(void) {}  /* TODO: implement */
void wubu_can(void) {}  /* TODO: implement */
void wubu_chanmap(void) {}  /* TODO: implement */
void wubu_clock(void) {}  /* TODO: implement */
void wubu_cmb(void) {}  /* TODO: implement */
void wubu_codec(void) {}  /* TODO: implement */
void wubu_codecgraph(void) {}  /* TODO: implement */
void wubu_colormgmt(void) {}  /* TODO: implement */
void wubu_compress(void) {}  /* TODO: implement */
void wubu_compressor(void) {}  /* TODO: implement */
void wubu_compute(void) {}  /* TODO: implement */
void wubu_computectx(void) {}  /* TODO: implement */
void wubu_cuda(void) {}  /* TODO: implement */
void wubu_dapm(void) {}  /* TODO: implement */
void wubu_dapmwidget(void) {}  /* TODO: implement */
void wubu_dappath(void) {}  /* TODO: implement */
void wubu_dax(void) {}  /* TODO: implement */
void wubu_ddcci(void) {}  /* TODO: implement */
void wubu_decode(void) {}  /* TODO: implement */
void wubu_dedup(void) {}  /* TODO: implement */
void wubu_devmapper(void) {}  /* TODO: implement */
void wubu_display(void) {}  /* TODO: implement */
void wubu_dmcrypt(void) {}  /* TODO: implement */
void wubu_drm(void) {}  /* TODO: implement */
void wubu_drmx(void) {}  /* TODO: implement */
void wubu_dspgraph(void) {}  /* TODO: implement */
void wubu_dspmode(void) {}  /* TODO: implement */
void wubu_dsptrace(void) {}  /* TODO: implement */
void wubu_ducking(void) {}  /* TODO: implement */
void wubu_encode(void) {}  /* TODO: implement */
void wubu_eq(void) {}  /* TODO: implement */
void wubu_fantml(void) {}  /* TODO: implement */
void wubu_fbcon(void) {}  /* TODO: implement */
void wubu_fc(void) {}  /* TODO: implement */
void wubu_fence(void) {}  /* TODO: implement */
void wubu_fencesync(void) {}  /* TODO: implement */
void wubu_filter(void) {}  /* TODO: implement */
void wubu_fingerprint(void) {}  /* TODO: implement */
void wubu_flush(void) {}  /* TODO: implement */
void wubu_flush2(void) {}  /* TODO: implement */
void wubu_fpga(void) {}  /* TODO: implement */
void wubu_fusefs(void) {}  /* TODO: implement */
void wubu_fw(void) {}  /* TODO: implement */
void wubu_gadget(void) {}  /* TODO: implement */
void wubu_gamepad(void) {}  /* TODO: implement */
void wubu_gamepadbm(void) {}  /* TODO: implement */
void wubu_gamepaddz(void) {}  /* TODO: implement */
void wubu_gpuband(void) {}  /* TODO: implement */
void wubu_gpucsched(void) {}  /* TODO: implement */
void wubu_gpudc(void) {}  /* TODO: implement */
void wubu_gpufw(void) {}  /* TODO: implement */
void wubu_gpufwupd(void) {}  /* TODO: implement */
void wubu_gpukms(void) {}  /* TODO: implement */
void wubu_gpumem(void) {}  /* TODO: implement */
void wubu_gpurst(void) {}  /* TODO: implement */
void wubu_gpusched(void) {}  /* TODO: implement */
void wubu_gpusensor(void) {}  /* TODO: implement */
void wubu_gpushader(void) {}  /* TODO: implement */
void wubu_gt2xx(void) {}  /* TODO: implement */
void wubu_hdr(void) {}  /* TODO: implement */
void wubu_hid(void) {}  /* TODO: implement */
void wubu_hid_driver_for(void) {}  /* TODO: implement */
void wubu_hid_ff(void) {}  /* TODO: implement */
void wubu_hid_generic(void) {}  /* TODO: implement */
void wubu_hid_multitouch(void) {}  /* TODO: implement */
void wubu_hid_present(void) {}  /* TODO: implement */
void wubu_hid_probe(void) {}  /* TODO: implement */
void wubu_hid_summary(void) {}  /* TODO: implement */
void wubu_hid_vendor(void) {}  /* TODO: implement */
void wubu_hidadv(void) {}  /* TODO: implement */
void wubu_ieccontrol(void) {}  /* TODO: implement */
void wubu_ima(void) {}  /* TODO: implement */
void wubu_input(void) {}  /* TODO: implement */
void wubu_instinct(void) {}  /* TODO: implement */
void wubu_intel_gma(void) {}  /* TODO: implement */
void wubu_intel_icelake(void) {}  /* TODO: implement */
void wubu_intel_skylake(void) {}  /* TODO: implement */
void wubu_intelgpu(void) {}  /* TODO: implement */
void wubu_ioprio(void) {}  /* TODO: implement */
void wubu_iosched(void) {}  /* TODO: implement */
void wubu_jack(void) {}  /* TODO: implement */
void wubu_jackdetect(void) {}  /* TODO: implement */
void wubu_jackimpedance(void) {}  /* TODO: implement */
void wubu_jackstate(void) {}  /* TODO: implement */
void wubu_kv_base(void) {}  /* TODO: implement */
void wubu_kv_capacity(void) {}  /* TODO: implement */
void wubu_kvfs(void) {}  /* TODO: implement */
void wubu_kvfs_handle_t(void) {}  /* TODO: implement */
void wubu_kvfs_t(void) {}  /* TODO: implement */
void wubu_leaudio(void) {}  /* TODO: implement */
void wubu_leaudioldr(void) {}  /* TODO: implement */
void wubu_loudness(void) {}  /* TODO: implement */
void wubu_lvm(void) {}  /* TODO: implement */
void wubu_mali_g52(void) {}  /* TODO: implement */
void wubu_mali_g720(void) {}  /* TODO: implement */
void wubu_mali_g77(void) {}  /* TODO: implement */
void wubu_mdraid(void) {}  /* TODO: implement */
void wubu_mem(void) {}  /* TODO: implement */
void wubu_memmgr(void) {}  /* TODO: implement */
void wubu_mixergraph(void) {}  /* TODO: implement */
void wubu_mixgraph(void) {}  /* TODO: implement */
void wubu_mmu(void) {}  /* TODO: implement */
void wubu_mst(void) {}  /* TODO: implement */
void wubu_multigig(void) {}  /* TODO: implement */
void wubu_navi10(void) {}  /* TODO: implement */
void wubu_net(void) {}  /* TODO: implement */
void wubu_nfsclient(void) {}  /* TODO: implement */
void wubu_nfsmount(void) {}  /* TODO: implement */
void wubu_nicoffload(void) {}  /* TODO: implement */
void wubu_ns(void) {}  /* TODO: implement */
void wubu_nvidia_fermi(void) {}  /* TODO: implement */
void wubu_nvidia_kepler(void) {}  /* TODO: implement */
void wubu_nvidia_maxwell(void) {}  /* TODO: implement */
void wubu_nvidia_pascal(void) {}  /* TODO: implement */
void wubu_nvidia_turing(void) {}  /* TODO: implement */
void wubu_nvidia_volta(void) {}  /* TODO: implement */
void wubu_nvme_gen4(void) {}  /* TODO: implement */
void wubu_nvme_gen5(void) {}  /* TODO: implement */
void wubu_nvmehotplug(void) {}  /* TODO: implement */
void wubu_nvmepower(void) {}  /* TODO: implement */
void wubu_opencl(void) {}  /* TODO: implement */
void wubu_overclock(void) {}  /* TODO: implement */
void wubu_panel(void) {}  /* TODO: implement */
void wubu_pcipme(void) {}  /* TODO: implement */
void wubu_pcmlink(void) {}  /* TODO: implement */
void wubu_pcmplugin(void) {}  /* TODO: implement */
void wubu_pcmring(void) {}  /* TODO: implement */
void wubu_pd(void) {}  /* TODO: implement */
void wubu_pdpolicy(void) {}  /* TODO: implement */
void wubu_perf(void) {}  /* TODO: implement */
void wubu_perfmon(void) {}  /* TODO: implement */
void wubu_peripheral(void) {}  /* TODO: implement */
void wubu_phy(void) {}  /* TODO: implement */
void wubu_pm(void) {}  /* TODO: implement */
void wubu_pmicaudio(void) {}  /* TODO: implement */
void wubu_porttiming(void) {}  /* TODO: implement */
void wubu_power(void) {}  /* TODO: implement */
void wubu_powergate(void) {}  /* TODO: implement */
void wubu_powervr(void) {}  /* TODO: implement */
void wubu_probe(void) {}  /* TODO: implement */
void wubu_psr(void) {}  /* TODO: implement */
void wubu_ptp(void) {}  /* TODO: implement */
void wubu_ptp_sync(void) {}  /* TODO: implement */
void wubu_qos(void) {}  /* TODO: implement */
void wubu_quadro(void) {}  /* TODO: implement */
void wubu_radeon_5000(void) {}  /* TODO: implement */
void wubu_radeon_6000(void) {}  /* TODO: implement */
void wubu_radeon_legacy(void) {}  /* TODO: implement */
void wubu_raid(void) {}  /* TODO: implement */
void wubu_raid5(void) {}  /* TODO: implement */
void wubu_raidcache(void) {}  /* TODO: implement */
void wubu_rdma(void) {}  /* TODO: implement */
void wubu_rendernode(void) {}  /* TODO: implement */
void wubu_renoir(void) {}  /* TODO: implement */
void wubu_rtc(void) {}  /* TODO: implement */
void wubu_rtc_driver_for(void) {}  /* TODO: implement */
void wubu_rtc_has_cooling(void) {}  /* TODO: implement */
void wubu_rtc_has_thermal(void) {}  /* TODO: implement */
void wubu_rtc_present(void) {}  /* TODO: implement */
void wubu_rtc_probe(void) {}  /* TODO: implement */
void wubu_rtc_summary(void) {}  /* TODO: implement */
void wubu_rtc_thermal_for(void) {}  /* TODO: implement */
void wubu_rtc_thermal_zones(void) {}  /* TODO: implement */
void wubu_samplerate(void) {}  /* TODO: implement */
void wubu_sata(void) {}  /* TODO: implement */
void wubu_securekey(void) {}  /* TODO: implement */
void wubu_sensor(void) {}  /* TODO: implement */
void wubu_smart(void) {}  /* TODO: implement */
void wubu_smc(void) {}  /* TODO: implement */
void wubu_smr(void) {}  /* TODO: implement */
void wubu_spdif(void) {}  /* TODO: implement */
void wubu_spdifrx(void) {}  /* TODO: implement */
void wubu_spdifstatus(void) {}  /* TODO: implement */
void wubu_spdiftx(void) {}  /* TODO: implement */
void wubu_storage(void) {}  /* TODO: implement */
void wubu_storagesched(void) {}  /* TODO: implement */
void wubu_switchdev(void) {}  /* TODO: implement */
void wubu_thermal(void) {}  /* TODO: implement */
void wubu_thermalthrottle(void) {}  /* TODO: implement */
void wubu_touch(void) {}  /* TODO: implement */
void wubu_tpm(void) {}  /* TODO: implement */
void wubu_trim(void) {}  /* TODO: implement */
void wubu_uac(void) {}  /* TODO: implement */
void wubu_uas(void) {}  /* TODO: implement */
void wubu_ucode(void) {}  /* TODO: implement */
void wubu_usb4(void) {}  /* TODO: implement */
void wubu_usbf(void) {}  /* TODO: implement */
void wubu_vblank(void) {}  /* TODO: implement */
void wubu_vc4(void) {}  /* TODO: implement */
void wubu_vc6(void) {}  /* TODO: implement */
void wubu_vega(void) {}  /* TODO: implement */
void wubu_video(void) {}  /* TODO: implement */
void wubu_virt(void) {}  /* TODO: implement */
void wubu_vlanaudio(void) {}  /* TODO: implement */
void wubu_volcanic_islands(void) {}  /* TODO: implement */
void wubu_voltagectl(void) {}  /* TODO: implement */
void wubu_vpudecode(void) {}  /* TODO: implement */
void wubu_vpuencode(void) {}  /* TODO: implement */
void wubu_vram(void) {}  /* TODO: implement */
void wubu_vrr(void) {}  /* TODO: implement */
void wubu_vulkan14(void) {}  /* TODO: implement */
void wubu_wifi7(void) {}  /* TODO: implement */
void wubu_wifi_reg(void) {}  /* TODO: implement */
void wubu_wifiutil(void) {}  /* TODO: implement */
void wubu_wine_env(void) {}  /* TODO: implement */
void wubu_writeback(void) {}  /* TODO: implement */
void wubu_xe3(void) {}  /* TODO: implement */
void wubu_znszone(void) {}  /* TODO: implement */
void wubu_zoneappend(void) {}  /* TODO: implement */
void wubu_zonecap(void) {}  /* TODO: implement */
void wubu_zoned(void) {}  /* TODO: implement */
void wubu_zonefmt(void) {}  /* TODO: implement */
void wubu_zonseqwrite(void) {}  /* TODO: implement */
