/*
 * vsl_syscall_list.h - Master syscall list for VSL
 * Generated from ReactOS ntoskrnl/sysfuncs.lst (NT 5.2/Vista parity)
 *
 * Usage:
 *   #define VSL_SYSCALL(name, nargs) ...
 *   #include "vsl_syscall_list.h"
 *   #undef VSL_SYSCALL
 */

VSL_SYSCALL(vsl_sys_accept, 6)  // NtAcceptConnectPort
VSL_SYSCALL(vsl_sys_nosys, 8)  // NtAccessCheck
VSL_SYSCALL(vsl_sys_nosys, 11)  // NtAccessCheckAndAuditAlarm
VSL_SYSCALL(vsl_sys_nosys, 11)  // NtAccessCheckByType
VSL_SYSCALL(vsl_sys_nosys, 16)  // NtAccessCheckByTypeAndAuditAlarm
VSL_SYSCALL(vsl_sys_nosys, 11)  // NtAccessCheckByTypeResultList
VSL_SYSCALL(vsl_sys_nosys, 16)  // NtAccessCheckByTypeResultListAndAuditAlarm
VSL_SYSCALL(vsl_sys_nosys, 17)  // NtAccessCheckByTypeResultListAndAuditAlarmByHandle
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtAddAtom
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtAddBootEntry
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtAddDriverEntry
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtAdjustGroupsToken
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtAdjustPrivilegesToken
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtAlertResumeThread
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtAlertThread
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtAllocateLocallyUniqueId
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtAllocateUserPhysicalPages
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtAllocateUuids
VSL_SYSCALL(vsl_sys_mmap, 6)  // NtAllocateVirtualMemory
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtApphelpCacheControl
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtAreMappedFilesTheSame
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtAssignProcessToJobObject
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtCallbackReturn
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtCancelDeviceWakeupRequest
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtCancelIoFile
VSL_SYSCALL(vsl_sys_timer_delete, 2)  // NtCancelTimer
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtClearEvent
VSL_SYSCALL(vsl_sys_close, 1)  // NtClose
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtCloseObjectAuditAlarm
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtCompactKeys
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtCompareTokens
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtCompleteConnectPort
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtCompressKey
VSL_SYSCALL(vsl_sys_connect, 8)  // NtConnectPort
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtContinue
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtCreateDebugObject
VSL_SYSCALL(vsl_sys_mkdir, 3)  // NtCreateDirectoryObject
VSL_SYSCALL(vsl_sys_eventfd, 5)  // NtCreateEvent
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtCreateEventPair
VSL_SYSCALL(vsl_sys_open, 11)  // NtCreateFile
VSL_SYSCALL(vsl_sys_epoll_create, 4)  // NtCreateIoCompletion
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtCreateJobObject
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtCreateJobSet
VSL_SYSCALL(vsl_sys_openat, 7)  // NtCreateKey
VSL_SYSCALL(vsl_sys_nosys, 8)  // NtCreateMailslotFile
VSL_SYSCALL(vsl_sys_futex, 4)  // NtCreateMutant
VSL_SYSCALL(vsl_sys_pipe, 14)  // NtCreateNamedPipeFile
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtCreatePagingFile
VSL_SYSCALL(vsl_sys_socketpair, 5)  // NtCreatePort
VSL_SYSCALL(vsl_sys_fork, 8)  // NtCreateProcess
VSL_SYSCALL(vsl_sys_clone, 9)  // NtCreateProcessEx
VSL_SYSCALL(vsl_sys_nosys, 9)  // NtCreateProfile
VSL_SYSCALL(vsl_sys_mmap, 7)  // NtCreateSection
VSL_SYSCALL(vsl_sys_futex, 5)  // NtCreateSemaphore
VSL_SYSCALL(vsl_sys_symlink, 4)  // NtCreateSymbolicLinkObject
VSL_SYSCALL(vsl_sys_clone, 8)  // NtCreateThread
VSL_SYSCALL(vsl_sys_timerfd_create, 4)  // NtCreateTimer
VSL_SYSCALL(vsl_sys_nosys, 13)  // NtCreateToken
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtCreateWaitablePort
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtDebugActiveProcess
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtDebugContinue
VSL_SYSCALL(vsl_sys_nanosleep, 2)  // NtDelayExecution
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtDeleteAtom
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtDeleteBootEntry
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtDeleteDriverEntry
VSL_SYSCALL(vsl_sys_unlink, 1)  // NtDeleteFile
VSL_SYSCALL(vsl_sys_unlink, 1)  // NtDeleteKey
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtDeleteObjectAuditAlarm
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtDeleteValueKey
VSL_SYSCALL(vsl_sys_ioctl, 10)  // NtDeviceIoControlFile
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtDisplayString
VSL_SYSCALL(vsl_sys_dup, 7)  // NtDuplicateObject
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtDuplicateToken
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtEnumerateBootEntries
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtEnumerateDriverEntries
VSL_SYSCALL(vsl_sys_getdents, 6)  // NtEnumerateKey
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtEnumerateSystemEnvironmentValuesEx
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtEnumerateValueKey
VSL_SYSCALL(vsl_sys_mremap, 2)  // NtExtendSection
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtFilterToken
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtFindAtom
VSL_SYSCALL(vsl_sys_fsync, 2)  // NtFlushBuffersFile
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtFlushInstructionCache
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtFlushKey
VSL_SYSCALL(vsl_sys_msync, 4)  // NtFlushVirtualMemory
VSL_SYSCALL(vsl_sys_nosys, 0)  // NtFlushWriteBuffer
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtFreeUserPhysicalPages
VSL_SYSCALL(vsl_sys_munmap, 4)  // NtFreeVirtualMemory
VSL_SYSCALL(vsl_sys_ioctl, 10)  // NtFsControlFile
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtGetContextThread
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtGetDevicePowerState
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtGetPlugPlayEvent
VSL_SYSCALL(vsl_sys_nosys, 7)  // NtGetWriteWatch
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtImpersonateAnonymousToken
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtImpersonateClientOfPort
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtImpersonateThread
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtInitializeRegistry
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtInitiatePowerAction
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtIsProcessInJob
VSL_SYSCALL(vsl_sys_nosys, 0)  // NtIsSystemResumeAutomatic
VSL_SYSCALL(vsl_sys_listen, 2)  // NtListenPort
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtLoadDriver
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtLoadKey
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtLoadKey2
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtLoadKeyEx
VSL_SYSCALL(vsl_sys_fcntl, 10)  // NtLockFile
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtLockProductActivationKeys
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtLockRegistryKey
VSL_SYSCALL(vsl_sys_mlock, 4)  // NtLockVirtualMemory
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtMakePermanentObject
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtMakeTemporaryObject
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtMapUserPhysicalPages
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtMapUserPhysicalPagesScatter
VSL_SYSCALL(vsl_sys_mmap, 10)  // NtMapViewOfSection
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtModifyBootEntry
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtModifyDriverEntry
VSL_SYSCALL(vsl_sys_nosys, 9)  // NtNotifyChangeDirectoryFile
VSL_SYSCALL(vsl_sys_inotify_add_watch, 10)  // NtNotifyChangeKey
VSL_SYSCALL(vsl_sys_inotify_add_watch, 12)  // NtNotifyChangeMultipleKeys
VSL_SYSCALL(vsl_sys_openat, 3)  // NtOpenDirectoryObject
VSL_SYSCALL(vsl_sys_open, 3)  // NtOpenEvent
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtOpenEventPair
VSL_SYSCALL(vsl_sys_open, 6)  // NtOpenFile
VSL_SYSCALL(vsl_sys_open, 3)  // NtOpenIoCompletion
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtOpenJobObject
VSL_SYSCALL(vsl_sys_openat, 3)  // NtOpenKey
VSL_SYSCALL(vsl_sys_open, 3)  // NtOpenMutant
VSL_SYSCALL(vsl_sys_nosys, 12)  // NtOpenObjectAuditAlarm
VSL_SYSCALL(vsl_sys_open, 4)  // NtOpenProcess
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtOpenProcessToken
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtOpenProcessTokenEx
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtOpenSection
VSL_SYSCALL(vsl_sys_open, 3)  // NtOpenSemaphore
VSL_SYSCALL(vsl_sys_readlink, 3)  // NtOpenSymbolicLinkObject
VSL_SYSCALL(vsl_sys_open, 4)  // NtOpenThread
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtOpenThreadToken
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtOpenThreadTokenEx
VSL_SYSCALL(vsl_sys_open, 3)  // NtOpenTimer
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtPlugPlayControl
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtPowerInformation
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtPrivilegeCheck
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtPrivilegeObjectAuditAlarm
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtPrivilegedServiceAuditAlarm
VSL_SYSCALL(vsl_sys_mprotect, 5)  // NtProtectVirtualMemory
VSL_SYSCALL(vsl_sys_eventfd_write, 2)  // NtPulseEvent
VSL_SYSCALL(vsl_sys_stat, 2)  // NtQueryAttributesFile
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtQueryBootEntryOrder
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtQueryBootOptions
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtQueryDebugFilterState
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtQueryDefaultLocale
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtQueryDefaultUILanguage
VSL_SYSCALL(vsl_sys_getdents, 11)  // NtQueryDirectoryFile
VSL_SYSCALL(vsl_sys_getdents, 7)  // NtQueryDirectoryObject
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtQueryDriverEntryOrder
VSL_SYSCALL(vsl_sys_getxattr, 9)  // NtQueryEaFile
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryEvent
VSL_SYSCALL(vsl_sys_stat, 2)  // NtQueryFullAttributesFile
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryInformationAtom
VSL_SYSCALL(vsl_sys_fstat, 5)  // NtQueryInformationFile
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryInformationJobObject
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryInformationPort
VSL_SYSCALL(vsl_sys_proc_info, 5)  // NtQueryInformationProcess
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryInformationThread
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryInformationToken
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtQueryInstallUILanguage
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtQueryIntervalProfile
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryIoCompletion
VSL_SYSCALL(vsl_sys_getdents, 5)  // NtQueryKey
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtQueryMultipleValueKey
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryMutant
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryObject
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtQueryOpenSubKeys
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtQueryOpenSubKeysEx
VSL_SYSCALL(vsl_sys_clock_gettime, 2)  // NtQueryPerformanceCounter
VSL_SYSCALL(vsl_sys_nosys, 9)  // NtQueryQuotaInformationFile
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQuerySection
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQuerySecurityObject
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQuerySemaphore
VSL_SYSCALL(vsl_sys_readlink, 3)  // NtQuerySymbolicLinkObject
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtQuerySystemEnvironmentValue
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQuerySystemEnvironmentValueEx
VSL_SYSCALL(vsl_sys_sysinfo, 4)  // NtQuerySystemInformation
VSL_SYSCALL(vsl_sys_clock_gettime, 1)  // NtQuerySystemTime
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueryTimer
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtQueryTimerResolution
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtQueryValueKey
VSL_SYSCALL(vsl_sys_proc_vm_info, 6)  // NtQueryVirtualMemory
VSL_SYSCALL(vsl_sys_statfs, 5)  // NtQueryVolumeInformationFile
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtQueueApcThread
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtRaiseException
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtRaiseHardError
VSL_SYSCALL(vsl_sys_read, 9)  // NtReadFile
VSL_SYSCALL(vsl_sys_readv, 9)  // NtReadFileScatter
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtReadRequestData
VSL_SYSCALL(vsl_sys_process_vm_readv, 5)  // NtReadVirtualMemory
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtRegisterThreadTerminatePort
VSL_SYSCALL(vsl_sys_futex, 2)  // NtReleaseMutant
VSL_SYSCALL(vsl_sys_futex, 3)  // NtReleaseSemaphore
VSL_SYSCALL(vsl_sys_epoll_wait, 5)  // NtRemoveIoCompletion
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtRemoveProcessDebug
VSL_SYSCALL(vsl_sys_rename, 2)  // NtRenameKey
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtReplaceKey
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtReplyPort
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtReplyWaitReceivePort
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtReplyWaitReceivePortEx
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtReplyWaitReplyPort
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtRequestDeviceWakeup
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtRequestPort
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtRequestWaitReplyPort
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtRequestWakeupLatency
VSL_SYSCALL(vsl_sys_eventfd, 2)  // NtResetEvent
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtResetWriteWatch
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtRestoreKey
VSL_SYSCALL(vsl_sys_kill, 1)  // NtResumeProcess
VSL_SYSCALL(vsl_sys_kill, 2)  // NtResumeThread
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSaveKey
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtSaveKeyEx
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtSaveMergedKeys
VSL_SYSCALL(vsl_sys_nosys, 9)  // NtSecureConnectPort
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetBootEntryOrder
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetBootOptions
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetContextThread
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtSetDebugFilterState
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetDefaultHardErrorPort
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetDefaultLocale
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetDefaultUILanguage
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetDriverEntryOrder
VSL_SYSCALL(vsl_sys_setxattr, 4)  // NtSetEaFile
VSL_SYSCALL(vsl_sys_eventfd_write, 2)  // NtSetEvent
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetEventBoostPriority
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetHighEventPair
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetHighWaitLowEventPair
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtSetInformationDebugObject
VSL_SYSCALL(vsl_sys_fcntl, 5)  // NtSetInformationFile
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtSetInformationJobObject
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtSetInformationKey
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtSetInformationObject
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtSetInformationProcess
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtSetInformationThread
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtSetInformationToken
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetIntervalProfile
VSL_SYSCALL(vsl_sys_epoll_ctl, 5)  // NtSetIoCompletion
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtSetLdtEntries
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetLowEventPair
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetLowWaitHighEventPair
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtSetQuotaInformationFile
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtSetSecurityObject
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetSystemEnvironmentValue
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtSetSystemEnvironmentValueEx
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtSetSystemInformation
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtSetSystemPowerState
VSL_SYSCALL(vsl_sys_clock_settime, 2)  // NtSetSystemTime
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtSetThreadExecutionState
VSL_SYSCALL(vsl_sys_timerfd_settime, 7)  // NtSetTimer
VSL_SYSCALL(vsl_sys_nosys, 3)  // NtSetTimerResolution
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtSetUuidSeed
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtSetValueKey
VSL_SYSCALL(vsl_sys_nosys, 5)  // NtSetVolumeInformationFile
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtShutdownSystem
VSL_SYSCALL(vsl_sys_futex_wait, 4)  // NtSignalAndWaitForSingleObject
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtStartProfile
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtStopProfile
VSL_SYSCALL(vsl_sys_kill, 1)  // NtSuspendProcess
VSL_SYSCALL(vsl_sys_kill, 2)  // NtSuspendThread
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtSystemDebugControl
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtTerminateJobObject
VSL_SYSCALL(vsl_sys_kill, 2)  // NtTerminateProcess
VSL_SYSCALL(vsl_sys_tgkill, 2)  // NtTerminateThread
VSL_SYSCALL(vsl_sys_nosys, 0)  // NtTestAlert
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtTraceEvent
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtTranslateFilePath
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtUnloadDriver
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtUnloadKey
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtUnloadKey2
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtUnloadKeyEx
VSL_SYSCALL(vsl_sys_fcntl, 5)  // NtUnlockFile
VSL_SYSCALL(vsl_sys_munlock, 4)  // NtUnlockVirtualMemory
VSL_SYSCALL(vsl_sys_munmap, 2)  // NtUnmapViewOfSection
VSL_SYSCALL(vsl_sys_nosys, 2)  // NtVdmControl
VSL_SYSCALL(vsl_sys_nosys, 4)  // NtWaitForDebugEvent
VSL_SYSCALL(vsl_sys_poll, 5)  // NtWaitForMultipleObjects
VSL_SYSCALL(vsl_sys_poll, 3)  // NtWaitForSingleObject
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtWaitHighEventPair
VSL_SYSCALL(vsl_sys_nosys, 1)  // NtWaitLowEventPair
VSL_SYSCALL(vsl_sys_write, 9)  // NtWriteFile
VSL_SYSCALL(vsl_sys_writev, 9)  // NtWriteFileGather
VSL_SYSCALL(vsl_sys_nosys, 6)  // NtWriteRequestData
VSL_SYSCALL(vsl_sys_process_vm_writev, 5)  // NtWriteVirtualMemory
VSL_SYSCALL(vsl_sys_sched_yield, 0)  // NtYieldExecution
VSL_SYSCALL(vsl_sys_futex, 4)  // NtCreateKeyedEvent
VSL_SYSCALL(vsl_sys_open, 3)  // NtOpenKeyedEvent
VSL_SYSCALL(vsl_sys_futex, 4)  // NtReleaseKeyedEvent
VSL_SYSCALL(vsl_sys_futex_wait, 4)  // NtWaitForKeyedEvent
VSL_SYSCALL(vsl_sys_nosys, 0)  // NtQueryPortInformationProcess
VSL_SYSCALL(vsl_sys_getcpu, 0)  // NtGetCurrentProcessorNumber
VSL_SYSCALL(vsl_sys_poll, 5)  // NtWaitForMultipleObjects32