/* wubu_deploy_gen.c -- Deployment config-file generators.
 *
 * Self-contained module extracted from wubu_deploy.c: Limine/WSL/Dockerfile/
 * macOS entitlements + Info.plist writers. Uses the shared wubu_deploy API
 * types + file/command util helpers via wubu_deploy_internal.h. Minimal includes.
 */

#include "wubu_deploy_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>

bool wubu_deploy_generate_limine_conf(const char* output_path, const char* kernel_cmdline) {
    char content[4096];
    snprintf(content, sizeof(content),
        "# WuBuOS Limine Configuration\n"
        "# Generated by wubu_deploy\n"
        "\n"
        "timeout: 5\n"
        "default_entry: WuBuOS\n"
        "\n"
        ":WuBuOS\n"
        "    protocol: linux\n"
        "    kernel_path: /boot/vmlinuz\n"
        "    cmdline: %s\n"
        "    module_path: /boot/initramfs.img\n"
        "\n"
        ":WuBuOS (Recovery)\n"
        "    protocol: linux\n"
        "    kernel_path: /boot/vmlinuz\n"
        "    cmdline: %s single\n"
        "    module_path: /boot/initramfs.img\n"
        "\n"
        ":Reboot\n"
        "    protocol: reboot\n"
        "\n"
        ":Power Off\n"
        "    protocol: poweroff\n",
        kernel_cmdline ? kernel_cmdline : "quiet loglevel=3",
        kernel_cmdline ? kernel_cmdline : "quiet loglevel=3");
    return write_file(output_path, content);
}

/* ============================================================
 * WSL Config Generation
 * ============================================================ */

bool wubu_deploy_generate_wsl_conf(const char* output_path, bool systemd) {
    char content[2048];
    snprintf(content, sizeof(content),
        "# WuBuOS WSL Configuration\n"
        "# Generated by wubu_deploy\n"
        "\n"
        "[boot]\n"
        "systemd=%s\n"
        "\n"
        "[automount]\n"
        "enabled=true\n"
        "root=/mnt/\n"
        "options=\"metadata,uid=1000,gid=1000,umask=022,fmask=111\"\n"
        "\n"
        "[network]\n"
        "generateResolvConf=true\n"
        "generateHosts=true\n"
        "\n"
        "[interop]\n"
        "enabled=true\n"
        "appendWindowsPath=true\n"
        "\n"
        "[user]\n"
        "default=wubu\n",
        systemd ? "true" : "false");
    return write_file(output_path, content);
}

/* ============================================================
 * Dockerfile Generation
 * ============================================================ */

bool wubu_deploy_generate_dockerfile(const wubu_oci_config_t* config, const char* output_path) {
    const char* base = config->base_image ? config->base_image : "scratch";
    const char* entrypoint = config->entrypoint ? config->entrypoint : "/usr/bin/wubu";
    
    char content[8192];
    char* p = content;
    p += snprintf(p, content + sizeof(content) - p,
        "# WuBuOS OCI Container Image\n"
        "# Generated by wubu_deploy\n"
        "# Build: docker build -t %s .\n"
        "\n"
        "FROM %s\n"
        "\n",
        config->image_name ? config->image_name : "wubuos:latest",
        base);

    if (strcmp(base, "scratch") == 0) {
        p += snprintf(p, content + sizeof(content) - p,
            "# Scratch base - copy rootfs\n"
            "COPY rootfs/ /\n"
            "\n");
    } else if (strstr(base, "alpine")) {
        p += snprintf(p, content + sizeof(content) - p,
            "# Alpine base - install dependencies\n"
            "RUN apk add --no-cache \\\n"
            "    libwayland-client \\\n"
            "    libxkbcommon \\\n"
            "    mesa-dri-gallium \\\n"
            "    libdrm \\\n"
            "    libgbm \\\n"
            "    fontconfig \\\n"
            "    ttf-dejavu \\\n"
            "    ca-certificates\n"
            "\n"
            "COPY rootfs/ /\n"
            "\n");
    } else if (strstr(base, "debian") || strstr(base, "ubuntu")) {
        p += snprintf(p, content + sizeof(content) - p,
            "# Debian/Ubuntu base - install dependencies\n"
            "RUN apt-get update && apt-get install -y --no-install-recommends \\\n"
            "    libwayland-client0 \\\n"
            "    libxkbcommon0 \\\n"
            "    mesa-vulkan-drivers \\\n"
            "    libdrm2 \\\n"
            "    libgbm1 \\\n"
            "    fontconfig \\\n"
            "    fonts-dejavu-core \\\n"
            "    ca-certificates \\\n"
            "    && rm -rf /var/lib/apt/lists/*\n"
            "\n"
            "COPY rootfs/ /\n"
            "\n");
    }

    /* Environment variables */
    if (config->env_vars) {
        for (int i = 0; config->env_vars[i]; i++) {
            p += snprintf(p, content + sizeof(content) - p, "ENV %s\n", config->env_vars[i]);
        }
        p += snprintf(p, content + sizeof(content) - p, "\n");
    }

    /* Exposed ports */
    if (config->ports) {
        for (int i = 0; config->ports[i]; i++) {
            p += snprintf(p, content + sizeof(content) - p, "EXPOSE %s\n", config->ports[i]);
        }
        p += snprintf(p, content + sizeof(content) - p, "\n");
    }

    /* Volumes */
    if (config->volumes) {
        for (int i = 0; config->volumes[i]; i++) {
            p += snprintf(p, content + sizeof(content) - p, "VOLUME [\"%s\"]\n", config->volumes[i]);
        }
        p += snprintf(p, content + sizeof(content) - p, "\n");
    }

    /* User */
    p += snprintf(p, content + sizeof(content) - p,
        "# Run as non-root user\n"
        "USER 1000:1000\n"
        "WORKDIR /home/wubu\n"
        "\n");

    /* Entrypoint */
    p += snprintf(p, content + sizeof(content) - p,
        "ENTRYPOINT [\"%s\"]\n"
        "CMD [\"-w\", \"1024\", \"768\"]\n",
        entrypoint);

    return write_file(output_path, content);
}

/* ============================================================
 * macOS Entitlements Generation
 * ============================================================ */

bool wubu_deploy_generate_entitlements(const wubu_macos_config_t* config, const char* output_path) {
    char content[4096];
    snprintf(content, sizeof(content),
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
        "<plist version=\"1.0\">\n"
        "<dict>\n"
        "    <key>com.apple.security.app-sandbox</key>\n"
        "    <true/>\n"
        "    <key>com.apple.security.hypervisor</key>\n"
        "    <true/>\n"
        "    <key>com.apple.security.vm.networking</key>\n"
        "%s"
        "    <key>com.apple.security.files.user-selected.read-write</key>\n"
        "    <true/>\n"
        "    <key>com.apple.security.device.usb</key>\n"
        "    <true/>\n"
        "    <key>com.apple.security.device.bluetooth</key>\n"
        "    <true/>\n"
        "</dict>\n"
        "</plist>\n",
        config->rosetta ? 
        "    <key>com.apple.security.cs.allow-dyld-environment-variables</key>\n"
        "    <true/>\n"
        "    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>\n"
        "    <true/>\n" : "");
    return write_file(output_path, content);
}

/* ============================================================
 * macOS Info.plist Generation
 * ============================================================ */

bool wubu_deploy_generate_infoplist(const wubu_macos_config_t* config, const char* output_path) {
    char content[4096];
    snprintf(content, sizeof(content),
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
        "<plist version=\"1.0\">\n"
        "<dict>\n"
        "    <key>CFBundleIdentifier</key>\n"
        "    <string>%s</string>\n"
        "    <key>CFBundleName</key>\n"
        "    <string>%s</string>\n"
        "    <key>CFBundleDisplayName</key>\n"
        "    <string>%s</string>\n"
        "    <key>CFBundleVersion</key>\n"
        "    <string>1.0.0</string>\n"
        "    <key>CFBundleShortVersionString</key>\n"
        "    <string>1.0.0</string>\n"
        "    <key>CFBundleExecutable</key>\n"
        "    <string>wubu-macos</string>\n"
        "    <key>CFBundlePackageType</key>\n"
        "    <string>APPL</string>\n"
        "    <key>CFBundleSignature</key>\n"
        "    <string>WUBU</string>\n"
        "    <key>LSMinimumSystemVersion</key>\n"
        "    <string>13.0</string>\n"
        "    <key>NSHighResolutionCapable</key>\n"
        "    <true/>\n"
        "    <key>LSApplicationCategoryType</key>\n"
        "    <string>public.app-category.utilities</string>\n"
        "</dict>\n"
        "</plist>\n",
        config->app_bundle_id ? config->app_bundle_id : "com.wubuos.app",
        config->app_name ? config->app_name : "WuBuOS",
        config->app_name ? config->app_name : "WuBuOS");
    return write_file(output_path, content);
}
