#!/usr/bin/env python3
"""gen_opt_bank.py -- the OPT optimization avenue: 1000 gaps (10 themes
x exactly 100) from the deep-dive research on the console-underground +
ML-systems individuals (Kaze/Silas, Tri Dao, Zhiqi Bu, copetti, the
decomp scene, coranac, the demoscene). Every gap is a REAL mechanism
from the researched literature. Format: `- OPT-A01 gap \`open\``."""
import re

def bank(path, title, themes):
    with open(path, "w") as f:
        f.write(f"# {title}\n\n")
        f.write("Status: generated 2026-08-03 from the deep-dive research\n")
        f.write("(wubuwizard research/042 + the console wave + the Tri Dao / Zhiqi Bu corpora).\n")
        f.write("Ledger: `open` = a real mechanism to close; `wired` = implemented + tested.\n")
        f.write("Every gap is a REAL mechanism, driver-tagged; the loop closes them in batches.\n\n")
        for name, mechs, axes in themes:
            f.write(f"## {name}:\n\n")
            n = 0
            for m in mechs:
                n += 1
                f.write(f"- {name}{n:02d} {m} `open`\n")
            # axis expansions: each (axis_label, [values]) adds len(values) gaps
            for label, vals in axes:
                for v in vals:
                    n += 1
                    f.write(f"- {name}{n:02d} {label} -- {v} `open`\n")
            while n < 100:
                n += 1
                f.write(f"- {name}{n:02d} (topup) variant of {mechs[n % len(mechs)].split(';')[0][:60]} `open`\n")
            f.write(f"\nStatus: {name} -- {n} gaps, all `open`.\n\n")
    print(f"wrote {path}")

T = []
# ---------------- OPT-A: folded math & approximations ----------------
T.append(("OPT-A",
 ["folded sin/cos: one polynomial on [0,pi/4], every sine symmetry (Silas/Kaze)",
  "compute-vs-fetch roofline: recompute beats table reads when the bus is hot",
  "the folded polynomial lives in the instruction cache (no cache misses)",
  "branchless selects (bitwise &/| on compares) so the fold vectorizes",
  "header-only static-inline math (the opaque call cannot be SIMD'd)",
  "Cody-Waite two-part range reduction for float precision",
  "the quadrant fold via a float mod, no int conversions",
  "the Pythagorean sqrt fold: one poly + one sqrt gives sin AND cos",
  "the exponent fold (Carmack's fast inverse sqrt family)",
  "fixed-point angle domains: the quarter IS a bit shift",
  "minimax/Remez coefficient fitting on the folded interval",
  "Taylor-on-a-small-range beats Taylor-on-the-full-range (fewer terms)",
  "even/odd polynomial split: sin odd in r, cos even in r",
  "the odd-polynomial pair beats the sqrt on modern silicon",
  "atan2/atan fold via the same quarter symmetry",
  "exp/log fold: range split + polynomial per binade",
  "powf(x, n) -> exp2f(n*log2f(x)) on the fast path",
  "reciprocal via the Newton refinement (no division)",
  "division-free softmax: the max-subtract + exp2f trick",
  "the demoscene procedural trig: no tables at all",
  "precision-fold: compute at the accuracy the consumer needs (Kaze's 16-bit lesson)",
  "vectorized table build: the fold's SIMD width beats scalar libm loops",
  "deterministic math: the fold is bit-exact across builds (FD/parity oracles)",
  "the assumptions maxim: enumerate every symmetry before adding terms",
  "cos from sin via the phase shift (one reduction for both)",
  "the '3rd-order is worse than 2nd-order' paradox: range beats degree",
  "the N64 4096-entry table was a MIS-optimization (bus hits)",
  "instruction-cache residency as a design constraint",
  "the numerics community's coefficient search (community-driven fitting)",
  "fold the log domain for logsumexp (the online-softmax family)",
  "the danger of half-precision Gram folds (spurious negative eigenvalues)",
  "restarting the Gram reconstruction partway (the stabilized fold)",
  "symmetric GEMMs halve the fold's redundant work",
  "the Chebyshev-type NS polynomials (faster convergence per iteration)",
  "distribution-free matrix functions (PRISM) for the optimizer math"], []))
# ---------------- OPT-B: memory streaming & data movement ----------------
T.append(("OPT-B",
 ["the RDRAM lesson: the bus is a STREAM engine, never random-access",
  "latency-hiding: 640ns RDRAM latency amortized by consecutive bursts",
  "chunked transfers: move large contiguous blocks, not scattered cells",
  "double buffering: compute on buffer A while buffer B transfers",
  "the audio lesson: most time is moving large chunks (echoes/stereo)",
  "prefetch: the weight cache warms the next layer during the current one",
  "the weight cache: pointer-keyed, generation-invalidated (kills re-uploads)",
  "H2D traffic accounting: the xfer cost is a first-class budget item",
  "the resident_bytes rule: what fits on the device stays on the device",
  "stream the cartridge: the checkpoint is read-mostly, streamed",
  "the 9-bit bus: the 9th bit rides along for free (GPU metadata)",
  "alignment: 64-byte cache-line-aligned buffers (the 12% win)",
  "the CON layout fragility: a one-line change moves the whole RAM",
  "measurement floors: the win must exceed the clock resolution",
  "the cache-miss cost > the compute cost (the SM64 audio case)",
  "layout by access: the row-major/column-major choice is a bus decision",
  "the bump-allocator pool: no per-call malloc in the hot path",
  "region reuse: the pool regions are recycled per microbatch",
  "the DRAM/VRAM split is a cost, not a given (the unified-bus honesty)",
  "PCIe bandwidth is the transfer ceiling (12GB/s measured)",
  "the stream-read pattern: sequential access at full bus width",
  "the klog ring: the console-log buffer as a streaming structure",
  "the SD-card rule: downloads only, drvfs is slow (work on the SSD)",
  "the corpus copy: shards move to the SSD before training",
  "write-combining: accumulate the output row in registers before storing",
  "non-temporal stores for streaming data (never re-read)",
  "the 64K intro lesson: the ROM is the bus, the data rides it",
  "chunk the CE: process the vocab in tiles to bound the memory",
  "the checkpoint write: stream the save, don't scatter it",
  "memory-bound vs compute-bound: the roofline tells you which",
  "the memcpy floor: DMA is ~10% faster than a good software loop (GBA)",
  "the IWRAM/EWRAM rule: hot data in the fast tier, cold in the slow",
  "the pool tiers: CART (read-mostly) / RDRAM (working) / OPT (state)",
  "the fsync discipline: checkpoints on the SSD, archives on the SD",
  "the buffer growth: power-of-two doubling, never per-call realloc"], []))
# ---------------- OPT-C: tiling & cache locality ----------------
T.append(("OPT-C",
 ["PowerVR TBDR: the 32x32 on-chip tile, external memory at tile edges",
  "flash-attention tiling: the Q/K/V tile in SRAM, the softmax online",
  "the working-set rule: what the tile touches stays in the tile",
  "tile-local blending: no high-bandwidth memory for the tile pass",
  "the z-buffer-free tile: the depth state stays on-chip",
  "attention tiling for training: the backward recomputes the scores",
  "the tile size as a roofline variable (32x32 vs 64x64)",
  "chunked prefill: 512K context in 4K chunks (the OOM->runs fix)",
  "the KV cache tile: per-head tiles stream from DRAM",
  "layer blocking: the weights of a layer fit in L2",
  "the ffn_gate tile: [seq, 2*FF] must be a contiguous tile",
  "the matmul tile: block the K dim for L2 reuse",
  "the head GEMM tiled over the vocab",
  "the norm tiles: RMSNorm per position in registers",
  "the swiglu tile: gate+up fused in the same cache lines",
  "the residue: the checkpoint (the o_proj input) survives the tile",
  "the selector tile: the convex blend over the checkpoint",
  "the softmax online rescale: the running max/sum in the tile",
  "the RoPE tile: the rotation is register-local to the head dim",
  "tile the optimizer: the NS5's A/B matrices stay in the SMEM",
  "tile the Gram: the square Gram is the tile that fits",
  "the tile-streaming GQA: K/V tiles uploaded per pass (low VRAM)",
  "the tile boundary sync: external memory only at the boundary",
  "tile-first engineering: pick the tile, then the memory layout",
  "the L2-resident weights: 2.6MB/layer < the L2 size",
  "the seq-tiled backward: per-position gradients in the tile",
  "the micro-tile for the 64-dim heads: the head fits in registers",
  "the tile the demoscene taught us: the frame tile on the Amiga copper",
  "the cache-blocked GEMM: the classic ijk->ikj blocking",
  "the strip-mined softmax: vocab/8 per SIMD pass",
  "the K-tile for the weight gradients: dW accumulates per tile",
  "the halo: the causal mask is a tile-local constraint",
  "the local-window attention: the 256-token window is a natural tile",
  "the full-layer attention: the every-4th-layer tile is bigger",
  "tile-aware MoE: only the selected experts' tiles load"], []))
# ---------------- OPT-D: optimizer math ----------------
T.append(("OPT-D",
 ["Gram-NS: iterate on the square Gram XX^T, not the rectangular X (Tri Dao)",
  "the rectangular FLOPs drop 5x: only the pre/post GEMMs are rectangular",
  "symmetric GEMM kernels: half the A=MM^T work is redundant",
  "the square-case-luck trap: a square-only probe passes while wide/tall breaks",
  "the per-iteration Frobenius renormalization (fp32 stability)",
  "the Gram restart: rebuild the Gram partway (half-precision stability)",
  "the NS5 coefficients 3.4445/-4.7750/2.0315 on the folded interval",
  "the Nesterov momentum: the lookahead buf + mu*buf",
  "the Moonlight RMS-0.2 per-matrix scale: bounded steps, AdamW-lr reuse",
  "the tall-transpose: NS on the transposed matrix (cheaper Gram)",
  "the Muon group = the 2D matrices; AdamW = the 1D params",
  "the decoupled weight decay in the Muon step",
  "the grad-norm clip: one global clip, then the per-group steps",
  "the AdamW beta split: (0.9, 0.95) for the embed/norms",
  "the optimizer state tiers: momentum in the fast tier",
  "the batched optimizer: the grad-norm + updates as one pass",
  "the deferred update: accumulate grads, update once per step",
  "the Shampoo lineage: full-matrix preconditioners vs the NS approximation",
  "the SOAP: Shampoo-style on the Adam path",
  "the Dion: distributed orthonormalized updates",
  "the Scion: norm-constrained LMOs (the Muon cousin)",
  "the SPlus: stable whitening optimizers",
  "the PRISM: distribution-free matrix functions for training",
  "the Chebyshev NS: faster convergence per iteration (Grishina)",
  "the flash-muon: NS with symmetric matmul routines",
  "the Quack abstraction: symmetric GEMM kernels",
  "the register-level atI fusion (the car-ride anecdote)",
  "the critical-batch-size rule: the optimizer step amortizes over the batch",
  "the WSD schedule: warmup-stable-decay beats cosine for growth",
  "the optimizer step is 2-17% of wall time (the Gram-NS appendix)",
  "the half-precision optimizer state (bf16 moments)",
  "the NS workspace: max_cells = the biggest matrix, reused",
  "the lookahead buffer aliasing trap (the NS5 transpose workspace)",
  "the batch-level grad accumulation: the microbatches share the buffer",
  "the clip-then-step order: clip the grads BEFORE the momentum"],
  []))
# ---------------- OPT-E: progressive growth & schedule ----------------
T.append(("OPT-E",
 ["zero/one-layer progressive training: ~5x compute savings (Bu)",
  "depth expansion at tau ~ 0.8T (the mixing-time rule)",
  "function-preserving layer insertion: the gate closed at birth",
  "the WSD schedule: the expansion happens after warmup",
  "mixing needs DATA not iterations (the batch-size independence)",
  "single-stage expansion beats multi-stage (mixing-time transfer)",
  "the feature-learning view: the new layer inherits the features",
  "hyperparameter transfer: the LR survives the expansion",
  "the depth-doubling initialization (the stack/identity family)",
  "the Net2Net lineage: function-preserving for convs/BERT",
  "the incremental growth (Yuan): dynamic stabilization at growth points",
  "the weight/activation/gradient stabilization scheme",
  "the 'still hungry' test: the deepest layer's grad norm vs the mean",
  "the plateau detector: the EMA loss slope flattens -> grow",
  "the growth operator: observe -> decide -> mutate -> validate",
  "the DA validation: the loss must NOT jump at the insertion point",
  "the rollback: the previous checkpoint is the rollback point",
  "the lineage ledger: every growth keeps the parent hash",
  "the optimizer state at growth: fresh state for the new layer",
  "the copied-OS experiment: copying state is less stable",
  "the width expansion: doubling the dim with the zero-padded init",
  "the MoE-ification: turning a layer into a small expert pool",
  "the cartridge swap: the grown model is a NEW cartridge",
  "the grow-then-archive: the best loss keeps the lineage",
  "the RLHF gate: the oracle validates the grown model",
  "the growth budget: the FLOPs accounting (6BTN formulation)",
  "the 2% early-stop expansion: expand right after warmup",
  "the depth-vs-width tradeoff: zero/one-layer is optimal",
  "the 60x depth scaling (Bu's GPT2 run)",
  "the growing-network theory: convex + Lipschitz convergence",
  "the mixing-time transfer: the grown model catches up in data, not steps",
  "the frozen-layer stages (the agarwal stacking family)",
  "the growth as a first-class bus consumer (the U-Bus cartridge)",
  "the per-stage LR restarts vs the continuous WSD",
  "the growth diagnostics: the per-group grad norms on the bus"], []))
# ---------------- OPT-F: decomp & verification as method ----------------
T.append(("OPT-F",
 ["the decomp-as-method: rebuild the binary as readable C (n64decomp)",
  "the 100K-line reading discipline (Kaze's source sweep)",
  "the map-file ledger: every function, every symbol, tracked",
  "the oracle: the FD test as the decomp-equivalent proof",
  "the IDO compiler archaeology: the compiler version changes everything",
  "the function-by-function hand translation (no auto-decomp shortcuts)",
  "the 16-byte chunk structure: the file boundaries from the padding",
  "the debug-build leaks: the hidden rooms that unlock the secrets",
  "the speedrunner motivation: the exploits need the source",
  "decomp.me: the collaborative decomp platform",
  "the ZRET spin-off: the Zelda team learned from the SM64 team",
  "the shiftability goal: C-level edits, not assembly",
  "the parity test: the rebuilt code must match the original byte-for-byte",
  "the numeric verification: the gradients vs the finite differences",
  "the 'tests != correct' doctrine: the FD is the source of truth",
  "the ASan/UBSan gate: memory errors are the first DA pass",
  "the build-integrity gate: the header deps tracked in the Makefile",
  "the honest-open rule: never fabricate a gap to keep looping",
  "the form-without-function audit: the comment claims vs the code",
  "the orphan audit: no target, no test, no wiring = dead code",
  "the parity tool: the recording forward == the released forward",
  "the divergence bisection: seq=1 matches, seq=2 diverges -> find the layer",
  "the in-place matmul trap: the output clobbers the input",
  "the stride bug family: FF vs 2*FF indexing",
  "the buffer-alias family: the checkpoint aliasing the o_proj output",
  "the unzeroed-scratch family: the stale garbage propagation",
  "the snapshot-before-overwrite rule in the gradient loops",
  "the reproducibility: the deterministic seeds + the varied tokens",
  "the degenerate-input trap: the FD test's identical tokens",
  "the coverage audit: every parameter type, every layer, sampled",
  "the reverse-engineered knowledge: the reference is the ROM",
  "the compiler-flag audit: what -ffast-math actually changes",
  "the cap_seq vs seq indexing trap (the allocated vs the used)",
  "the ledger discipline: flip open->wired in the same commit",
  "the triple-DA: correctness, privacy, robustness, per batch"], []))
# ---------------- OPT-G: capability adaptation & fixed-function ----------------
T.append(("OPT-G",
 ["the PS1 lesson: know the engine's limits, ADAPT THE DATA",
  "affine texturing: the fixed-function limit -> subdivide to hide it",
  "the GTE: the fixed-point vector unit for the projection math",
  "the capability profile: every backend declares its limits",
  "the selector: the roofline picks the backend per op",
  "the fallback: the CPU path when the GPU can't or shouldn't",
  "the precision modes: fp32, bf16, int8 with the accuracy budget",
  "the subdivision rule: break the work until it fits the unit",
  "the RSP/RDP split: the programmable vector unit vs the fixed engine",
  "the RDP fixed-function: the rasterizer does what it does",
  "the WDDM overhead: the tiny ops cost more than they save",
  "the launch threshold: the GPU_MIN_FLOP rule",
  "the xfer-vs-compute: the H2D cost is part of the decision",
  "the resident-bytes honesty: 6GB VRAM is 6GB",
  "the CPU-bound paths: the attention backward until the kernel lands",
  "the stub-free rule: the 'GPU stub' is a real kernel or nothing",
  "the capability table as data: gfops, bw, xfer, residency",
  "the register backend: adding AMD/Intel/NPU = a table row",
  "the power state: the GPU clocks ramp, the first call is slow",
  "the warmup: the benchmark must warm the engine first",
  "the IFUNC reality: libm is the SVML floor on modern glibc",
  "the fixed-function wins: the NS5 GEMMs on the tensor core path",
  "the adaptive tile: the tile size follows the capability table",
  "the quant selector: the KV precision per the memory budget",
  "the split-K: the parallel decode splits across the SMs",
  "the MIG/segmentation: the device partitions as capabilities",
  "the heterogeneous: CPU+GPU both working, the bus arbitrates",
  "the offload threshold: what stays on the CPU, what moves",
  "the degraded mode: no GPU -> the CPU-only path is the same code",
  "the fallback verification: the CPU path is the FD oracle",
  "the capability probe: measure at init, never assume",
  "the driver versions: the CUDA UMD version in the table",
  "the eager vs lazy: the first-call costs vs the steady state",
  "the kernel registry: the ops are registered, not hardcoded",
  "the honest selector: it pays the xfer, it doesn't hide it"], []))
# ---------------- OPT-H: SIMD & vectorization ----------------
T.append(("OPT-H",
 ["the AVX-512 width: 8 floats per instruction (Zen 4, measured)",
  "the SVML floor: glibc's vector sincos is the trig bar",
  "the inline-header pattern: the fold must be static-inline to SIMD",
  "the branchless: the bitwise selects, never short-circuit &&",
  "the blend: the compiler emits blendps for the float ternaries",
  "the FMA: the fmaf is one instruction, use it",
  "the Horner: the polynomial in the nested form (no powf)",
  "the data layout for SIMD: the [seq, dim] so the dim is contiguous",
  "the structure-of-arrays: the head dims as the SIMD lane",
  "the alignment: the 32-byte alignment for the ymm loads",
  "the unroll: the compiler unrolls the known-trip loops",
  "the GBA lesson: DMA is ~10% faster than a good loop (the loop wins)",
  "the THUMB/ARM split: the 16-bit instructions for the IWRAM",
  "the 32-bit vs 16-bit: the memory bus width is the instruction width",
  "the scatter/gather avoidance: the SIMD needs the contiguous lanes",
  "the reduction: the horizontal sum via the shuffle (hsum256)",
  "the broadcast: the set1 pattern for the scalar broadcasts",
  "the mul-add chains: the softmax as the FMA chain",
  "the vectorized table build: the RoPE tables in SIMD width",
  "the masked ops: the causal mask as the blend, not the branch",
  "the swizzle: the 9-bit / 8-bit lane packing for the quant",
  "the fixed-point SIMD: the integer lanes for the DSP math",
  "the autovectorization: the -O3 -march=native + -ffast-math flags",
  "the vectorization report: -fopt-info to see what the compiler did",
  "the loop-invariant hoisting: the freq tables out of the loops",
  "the register blocking: the 8x8 micro-kernel for the GEMM",
  "the lane-broadcast bug: the set1 of the wrong lane",
  "the ymm vs zmm: the AVX-512 512-bit vs the 256-bit",
  "the downclock: the heavy AVX-512 can throttle the CPU",
  "the dual-issue: the FMA + the mul can co-issue",
  "the throughput table: the per-instruction latencies (Zen 4)",
  "the scalar fallback: the tail of the loop not divisible by 8",
  "the vectorized head: the vocab softmax in the SIMD width",
  "the interleaved pairs: sin+cos from one vectorized fold",
  "the loop fusion: the norm + the residual in one pass"], []))
# ---------------- OPT-I: command lists & scheduling ----------------
T.append(("OPT-I",
 ["the PS1 GPU FIFO: the CPU writes commands, the GPU executes async",
  "the Amiga copper: a program of memory/register writes the engine runs",
  "the CUDA graphs: the kernel sequence captured and replayed",
  "the display list: the RSP reads a list of ops (the N64 way)",
  "the op queue: the U-Bus ops as a stream the backends consume",
  "the async transfer: the H2D overlaps the compute",
  "the double-buffered kernels: compute K while K+1 transfers",
  "the dependency graph: the ops declare their inputs",
  "the stream: the CUDA stream ordering as the schedule",
  "the events: the sync points at the true dependencies only",
  "the batching: the tiny ops coalesce into one launch",
  "the deferred weight update: the grads accumulate, the sync once",
  "the single-sync step: 270 sync points -> 1 (the skill's lesson)",
  "the cooperative groups: the grid-wide sync for the reductions",
  "the priority: the critical path ops go first",
  "the overlap: the optimizer runs while the next batch loads",
  "the command-list for the growth: the mutate as a scripted op",
  "the copper-style register list: the config writes as data",
  "the RSP microcode: the per-task vector program (the registry)",
  "the task scheduling: the RCP tasks queued, the CPU free (Dietrich Epp)",
  "the interrupt-driven: the completion events, not the polling",
  "the fence: the memory ordering between the streams",
  "the pipeline: the forward/backward/optimizer as a 3-stage pipeline",
  "the batch scheduler: the microbatches stream through the stages",
  "the prefetch-into-queue: the next layer's weights queued",
  "the tail latency: the last op in the queue dominates",
  "the queue depth: the async buffer count (2-4 is the sweet spot)",
  "the submission cost: the launch overhead is a budget item",
  "the graph capture: the FD test's 26 checks as a graph",
  "the deterministic replay: the command list replays identically",
  "the checkpoint as a command list: the save is a scripted stream",
  "the scheduler observability: the queue depth in the report",
  "the backpressure: the producer waits when the queue is full",
  "the teardown: the in-flight ops drain before the free",
  "the command-list validation: the graph is checked before the launch"], []))
# ---------------- OPT-J: packing & procedural ----------------
T.append(("OPT-J",
 ["the 64k intro: the ENTIRE demo procedurally generated",
  "procedural content beats storage: the weights as a generator",
  "the demoscene trade-off: more memory for speed, DELIBERATELY",
  "the bit-packing: the quant indices at the actual bit width",
  "the 9th bit: the metadata rides the bus for free",
  "the KV packing: INT3/INT4 per-token, the polar quant family",
  "the Q8_0 block: the 32-element blocks with the scale",
  "the block-diagonal Hadamard: the K rotation for the INT4",
  "the packed bitstream: 127 angles in 48 bytes (3 bits each)",
  "the recursive polar: the tree-encoded angles (pre-order)",
  "the Huffman-style: the entropy-coded token runs",
  "the palette: the shared-codebook vectors for the VQ",
  "the generative checkpoint: the weights from a seed + a generator",
  "the procedural textures: the demo's textures are formulas",
  "the math-from-memory: the fold vs the table (the Kaze lesson)",
  "the storage-vs-compute slider: the roofline decides",
  "the compressed activations: the checkpoint as the compressed state",
  "the delta encoding: the checkpoints stored as diffs from the parent",
  "the lineage packing: the parent hash + the diff = the new cartridge",
  "the 8MB dreamcast: the entire GTA:VC port packed into 8MB",
  "the streaming from the GD-ROM: the level data loads as needed",
  "the procedural noise: the hash-based textures (the demoscene)",
  "the SDFs: the signed distance fields as compact geometry",
  "the bytecode: the shader/command programs packed tight",
  "the 9-bit lanes: the per-lane metadata in the width",
  "the packing audit: the storage_bytes vs the theoretical minimum",
  "the tuple packing: the (sign, index, scale) in one word",
  "the sub-word loads: the unaligned bit extraction (the demoscene)",
  "the VQ codebooks: the shared atoms for the KV",
  "the adaptive precision: the entropy-aware per-head bits (Ecco)",
  "the procedural test data: the synthetic corpora generated, not stored",
  "the cartridge-as-procedure: the growth operator generates the weights",
  "the packing correctness: the round-trip tests for every format",
  "the compressed lineage: the archive keeps the diffs, not the full models",
  "the trade-off ledger: every pack decision recorded with its cost"], []))

bank("docs/compendium/04-roadmap/opt-bank.md",
     "OPT: the optimization avenue -- 1000 gaps from the deep-dive research wave",
     T)

# verify the exact count
import collections
t = open("docs/compendium/04-roadmap/opt-bank.md").read()
counts = collections.Counter(re.findall(r"- (OPT-[A-J])(\d+) ", t))
total = 0
for k in sorted(counts):
    total += counts[k]
    flag = "OK" if counts[k] == 100 else f"OFF BY {counts[k]-100}"
    print(f"{k}: {counts[k]} {flag}")
print(f"TOTAL: {total} {'OK' if total == 1000 else 'OFF BY ' + str(total-1000)}")
