#!/usr/bin/env python3
"""Avenue cores part 2: NW (network), KR (kernel), AIE (AI engine), HX (human)."""
import os, json
os.makedirs("docs/compendium/04-roadmap", exist_ok=True)

def bank(path, title, themes):
    T = [f"# {title}\n\nDate: 2026-08-02. Status: `open` / `wired`.\n"]
    for name, ttl, gaps, refs in themes:
        T.append(f"\n## {name}: {ttl}\nStatus: `open` = not yet built; `wired` = implemented + tested.\n### 7-hop convergence: {refs}\n")
        for i, g in enumerate(gaps, 1):
            T.append(f"- {name}{i:02d} {g} `open`\n")
        T.append(f"Status: `open` ({len(gaps)} gaps)\n")
    open(path, "w").write("".join(T))
    print(path, "core written")

NW = [
("NW-A", "The transport (TCP/QUIC)", [
 "TCP send/receive", "TCP window", "TCP congestion (cubic)", "TCP retransmit", "TCP timeouts", "TCP fast-recovery",
 "TCP keepalive", "TCP offload (the NIC)", "IO-TCP split stack", "QUIC the protocol", "QUIC handshake (1-RTT)",
 "QUIC 0-RTT", "QUIC streams", "QUIC flow control", "QUIC loss recovery", "QUIC congestion (BBR-ish)",
 "UDP the datagram", "UDP checksum", "UDP broadcast", "UDP multicast", "UDP the games path",
 "SCTP the future", "TLS the handshake", "TLS 1.3", "TLS the records", "TLS the session tickets",
 "MTU discovery", "Nagle vs delay", "The cork", "The zero-copy", "The socket API", "The listen backlog",
 "The accept loop", "The connection pool", "The idle timeout", "The half-close", "The RST handling",
 "The congestion state", "The pacing", "The BBR", "The loss-based", "The delay-based",
 "The transport test", "The transport bench", "The transport fuzz", "The transport energy",
], "TCP -> QUIC -> NIC offload (IO-TCP) -> the zero-copy path"),
("NW-B", "The internet layer", [
 "IPv4 the header", "IPv4 fragmentation", "IPv6 the header", "IPv6 extension headers", "IP routing",
 "The routing table", "The longest-prefix", "The ARP", "The ND (IPv6)", "The ICMP", "The ICMPv6",
 "The DHCP", "The DHCPv6", "The NAT", "The NAT64", "The firewall", "The netfilter-ish", "The iptables-ish",
 "The forwarding", "The encapsulation", "The tunnels", "The GRE", "The VXLAN", "The WireGuard",
 "The Tailscale", "The eBPF-ish", "The packet filter", "The rate limit", "The QoS classes",
 "The priority queue", "The traffic shaping", "The packet capture", "The pcap", "The loopback",
 "The multi-homing", "The failover", "The load balance", "The ECMP", "The BGP (future)",
 "The IP test", "The IP bench", "The IP fuzz", "The IP energy",
], "IPv4/v6 -> routing -> tunnels/VPN -> eBPF-ish filtering"),
("NW-C", "The application layer", [
 "HTTP/1.1 the parser", "HTTP/2 the frames", "HTTP/3 the QUIC", "The request/response", "The headers",
 "The cookies", "The cache", "The ETag", "The redirects", "The gzip transfer", "The keep-alive",
 "The chunked", "The WebSocket", "The SSE", "The REST the JSON", "The DNS the resolver", "The DNS cache",
 "The mDNS", "The DoH (future)", "The FTP (future)", "The SSH (future)", "The SMTP (future)", "The IMAP (future)",
 "The 9P over TCP", "The MQTT (future)", "The gRPC (future)", "The URL parse", "The URI encode",
 "The form parse", "The multipart", "The TLS SNI", "The virtual hosts", "The proxy", "The reverse proxy",
 "The load balancer", "The health check", "The retry", "The backoff", "The circuit breaker",
 "The app test", "The app bench", "The app fuzz", "The app energy",
], "HTTP/1.1 -> H2 -> H3/QUIC -> 9P-over-TCP -> the proxy/broker family"),
("NW-D", "The 9P networking", [
 "The 9P remote mount", "The 9P auth tokens", "The 9P transport", "The 9P keepalive", "The 9P reconnects",
 "The 9P caching", "The 9P flush", "The 9P watch", "The 9P quotas", "The 9P permissions",
 "The 9P the namespace merge", "The 9P the /net", "The 9P the remote OS", "The 9P the cluster",
 "The 9P the agent mesh", "The 9P the Bonzi remote", "The 9P the AGI remote", "The 9P the sync",
 "The 9P the security", "The 9P the tests",
], "the local 9P -> the remote 9P -> the agent mesh"),
("NW-E", "The protocols & formats", [
 "The JSON parse/write", "The JSON schema", "The BSON (future)", "The MessagePack (future)", "The Protobuf (future)",
 "The XML (future)", "The YAML", "The TOML", "The CSV", "The URL-encoded",
 "The Base64", "The Hex", "The UTF-8 validate", "The UTF-16", "The charset detect",
 "The MIME types", "The multipart", "The token auth", "The JWT (future)", "The OAuth (future)",
 "The serialization versioning", "The schema registry", "The binary format", "The endian", "The varint",
 "The protocol tests", "The protocol fuzz", "The protocol bench", "The protocol energy",
], "JSON/TOML/YAML -> varint/binary -> the versioned schemas"),
("NW-F", "The security & trust", [
 "The TLS chain verify", "The cert store", "The pinning", "The perfect-forward", "The cipher suites",
 "The AEAD (the ChaCha/AES)", "The hash (the SHA-256)", "The HMAC", "The key exchange", "The Ed25519 (future)",
 "The X25519 (future)", "The session keys", "The ticket rotation", "The renegotiation", "The ALPN",
 "The SNI", "The OCSP (future)", "The CT (future)", "The mTLS", "The client certs",
 "The token replay guard", "The CSRF (future)", "The rate limiting", "The fail2ban-ish", "The quarantine",
 "The threat model", "The attestation", "The EDR integration", "The audit log", "The forensics",
 "The security tests", "The security fuzz", "The security bench", "The security energy",
], "TLS1.3 -> AEAD -> attestation -> the EDR integration"),
("NW-G", "The mesh & the AGI swarm", [
 "The agent registry", "The agent discovery", "The agent heartbeat", "The agent lease", "The agent election",
 "The agent consensus (the RAFT-ish)", "The agent gossip", "The agent replication", "The agent partitions",
 "The agent merging", "The task distribution", "The task queue", "The task stealing", "The task results",
 "The task retry", "The task timeout", "The coordinator", "The worker pool", "The leader", "The followers",
 "The mesh the AGI goals", "The mesh the AGI closing", "The mesh the banks", "The mesh the sources",
 "The mesh the Bonzi", "The mesh the ledger", "The mesh the verifier", "The mesh the tests",
 "The mesh the bench", "The mesh the docs",
], "the agent mesh -> consensus -> the AGI swarm closing the banks"),
("NW-H", "The performance & observability", [
 "The throughput meter", "The latency meter", "The p50/p95/p99", "The bandwidth", "The packet rate",
 "The retransmit rate", "The RTT", "The jitter", "The queue depth", "The backpressure",
 "The tracing (the spans)", "The metrics (the counters)", "The logs (the structured)", "The dashboards",
 "The alerts", "The thresholds", "The baselines", "The regressions", "The profiling", "The flame graph (future)",
 "The zero-copy", "The splice", "The sendfile", "The MSG_ZEROCOPY (future)", "The ring buffers",
 "The poll (the epoll-ish)", "The io_uring (future)", "The multi-queue", "The RSS (future)", "The XDP (future)",
 "The perf tests", "The perf bench", "The perf fuzz", "The perf energy",
], "epoll -> ring buffers -> zero-copy -> the perf regression gate"),
("NW-I", "The offline & resilience", [
 "The offline queue", "The retry with backoff", "The exponential backoff", "The jitter", "The circuit breaker",
 "The bulkhead", "The timeout hierarchy", "The deadline propagation", "The fallback", "The degrade",
 "The cached responses", "The stale-while-revalidate", "The offline-first", "The sync on reconnect",
 "The conflict resolution", "The last-write-wins", "The CRDT (future)", "The idempotency", "The dedup",
 "The at-least-once", "The exactly-once (future)", "The outage mode", "The maintenance mode",
 "The read-only", "The graceful drain", "The graceful shutdown", "The reconnect storm guard",
 "The resilience tests", "The resilience fuzz", "The resilience bench", "The resilience energy",
], "backoff -> circuit breakers -> offline-first -> the CRDT future"),
("NW-J", "The network avenue engineering", [
 "The module registry", "The test matrix", "The protocol fuzz", "The bench harness", "The energy accounting",
 "The telemetry", "The watchdog", "The quarantine", "The docs spec", "The roadmap",
 "The cross-link to the FS", "The cross-link to the 9P", "The cross-link to the kernel", "The cross-link to the AGI",
 "The cross-link to the Bonzi", "The cross-link to the GUI", "The cross-link to the synthesis", "The cross-link to the wubuwizard",
 "The cross-link to the compendium", "The milestones",
], "the engineering discipline for the network avenue"),
]

KR = [
("KR-A", "The scheduler", [
 "The preemptive scheduler", "The tick (the PIT)", "The round-robin", "The priorities", "The nice levels",
 "The time slices", "The preemption points", "The voluntary yield", "The sleep queue", "The wakeup",
 "The wait queues", "The semaphores", "The mutexes", "The spinlocks", "The rwlocks", "The condition vars",
 "The futex-ish", "The RCU (future)", "The per-CPU runqueues", "The load balance", "The migration",
 "The idle loop", "The idle task", "The task states", "The task context switch", "The fxsave/fxrstor",
 "The lazy FPU", "The syscall entry", "The syscall exit", "The interrupt entry", "The interrupt exit",
 "The softirq-ish", "The tasklets-ish", "The work queues", "The timers", "The hrtimers", "The POSIX clocks",
 "The deadline scheduling (future)", "The CFS-ish (future)", "The EDF (future)", "The SCHED_FIFO",
 "The SCHED_RR", "The SCHED_OTHER", "The priority inheritance", "The PI chain", "The deadlock detect",
 "The lock ordering", "The scheduler tests", "The scheduler bench", "The scheduler fuzz", "The scheduler energy",
], "PIT tick -> preemption -> priority/inheritance -> the deadline future"),
("KR-B", "The memory management", [
 "The physical allocator", "The buddy", "The slabs (future)", "The page tables", "The 4-level walk",
 "The TLB", "The TLB shootdown", "The huge pages", "The 1G pages", "The kernel heap (mem_alloc)",
 "The malloc delegation", "The user heap", "The mmap", "The brk", "The stack guard", "The canaries",
 "The ASLR", "The NX bits", "The W^X", "The COW pages", "The demand paging", "The page faults",
 "The swap in", "The swap out", "The swap the 8-sector", "The OOM killer", "The memory cgroups",
 "The memory quotas", "The memory accounting", "The leak detect", "The heap walk", "The heap verify",
 "The fragmentation", "The compaction (future)", "The NUMA (future)", "The pinned pages",
 "The DMA pools", "The IOMMU (the console cmd)", "The ACPI memory map", "The e820", "The EFI map",
 "The reserved regions", "The memory tests", "The memory bench", "The memory fuzz", "The memory energy",
], "buddy -> paging -> swap -> the mem_alloc kernel heap"),
("KR-C", "The interrupts & devices", [
 "The IDT", "The vectors", "The PIC (legacy)", "The LAPIC", "The IOAPIC", "The EOI",
 "The spurious", "The nested (future)", "The IRQ affinity", "The MSI (future)", "The MSI-X (future)",
 "The handler registry", "The shared IRQs", "The bottom halves", "The deferred work", "The softirq-ish",
 "The tasklet-ish", "The workqueue", "The irqbalance-ish", "The irq stats", "The irq latency",
 "The device model", "The PCI", "The PCIe", "The BARs", "The MMIO",
 "The port I/O", "The DMA", "The scatter-gather", "The ring buffers", "The completion queues",
 "The poll mode", "The interrupt mode", "The hybrid", "The device tree (future)", "The ACPI",
 "The SMBIOS", "The HPET", "The PIT", "The RTC", "The CMOS",
 "The UART", "The PS/2", "The keyboard", "The mouse", "The display (the VBE)",
 "The AHCI", "The xHCI (future)", "The NVMe (future)", "The sound (future)", "The GPU (future)",
 "The device tests", "The device bench", "The device fuzz", "The device energy",
], "IDT/LAPIC -> PCI/MMIO -> AHCI/xHCI -> the ring buffers"),
("KR-D", "The syscalls & VSL", [
 "The syscall table", "The syscall args", "The syscall return", "The errno", "The syscall stack",
 "The kernel stack (the 8KB)", "The user/kernel boundary", "The copy-in", "The copy-out", "The access check",
 "The fd table", "The fd flags", "The fd dup", "The fd close", "The fd poll",
 "The file table", "The file ops", "The file offsets", "The file locks (future)", "The file leases (future)",
 "The process table", "The process spawn", "The exec", "The exit", "The wait",
 "The signals (future)", "The signal masks (future)", "The sigreturn (future)", "The ptrace (future)", "The seccomp",
 "The VSL the NT bridge", "The 297 NT syscalls", "The VSL the translation", "The VSL the adapters", "The VSL the errors",
 "The syscall tests", "The syscall bench", "The syscall fuzz", "The syscall energy",
], "the syscall table -> the kernel stacks -> the VSL NT bridge"),
("KR-E", "The boot & the firmware", [
 "The reset vector", "The real mode", "The protected mode", "The long mode", "The paging enable",
 "The GDT", "The IDT setup", "The crt0 (the A9 codes)", "The BSS clear", "The stack setup",
 "The kernel image", "The image start symbol", "The alignment assert", "The metal main",
 "The console init", "The serial init", "The klog", "The heap init", "The mem_alloc init",
 "The APIC init", "The timer init", "The scheduler start", "The verifier (the attestation)",
 "The measured boot", "The PCRs (the TPM future)", "The policy gate", "The promote", "The operate",
 "The AGI kernel boot", "The Colonel boot", "The console REPL", "The boot volume mount",
 "The FAT32 attach", "The AHCI init", "The userland start", "The GUI start (the hosted)",
 "The Wayland init (the hosted)", "The WuBuFW firmware", "The WuBuFW menu", "The WuBuFW verify",
 "The WuBuFW kernel load", "The dual boot (future)", "The UEFI (future)", "The Limine (future)",
 "The boot tests", "The boot bench", "The boot fuzz", "The boot energy",
], "crt0 A9 codes -> measured boot -> attestation -> the AGI kernel boot"),
("KR-F", "The SMP & the concurrency", [
 "The AP startup", "The SIPI", "The APIC ID", "The per-CPU areas", "The per-CPU runqueues",
 "The spinlock the cli", "The spinlock the ISR-safe", "The lock-free rings", "The RCU (future)",
 "The seq locks (future)", "The ticket locks (future)", "The mutex the task-safe", "The yield lock",
 "The condvar", "The barrier", "The atomics", "The cmpxchg", "The memory ordering",
 "The acquire/release", "The fence", "The TLB shootdown", "The IPI", "The reschedule IPI",
 "The CPU hotplug (future)", "The NUMA (future)", "The load balancing", "The work stealing",
 "The concurrency tests", "The concurrency stress", "The concurrency fuzz", "The concurrency energy",
], "SIPI -> per-CPU -> lock-free rings -> the task-safe mutex"),
("KR-G", "The security & the verifier", [
 "The measured boot", "The hash chain", "The SHA-256", "The HMAC", "The policy gate",
 "The attestation", "The TPM (future)", "The PCRs (future)", "The anti-rollback (future)", "The signed kernel",
 "The signed modules", "The signed apps", "The verifier the kernel", "The verifier the modules", "The verifier the apps",
 "The EDR the events", "The EDR the analytics", "The EDR the dashboard", "The audit log", "The forensics",
 "The permissions", "The capabilities (future)", "The MAC (future)", "The sandbox", "The seccomp",
 "The cgroups", "The namespace isolation", "The container security", "The memory safety", "The bounds checks",
 "The stack canaries", "The ASLR", "The W^X", "The kASLR (future)", "The ret2usr guard",
 "The SMEP/SMAP (future)", "The CET (future)", "The security tests", "The security fuzz", "The security bench",
 "The security energy",
], "measured boot -> attestation -> EDR -> the seccomp sandbox"),
("KR-H", "The drivers & the metal", [
 "The driver model", "The probe", "The remove", "The suspend (future)", "The resume (future)",
 "The PCI driver", "The AHCI driver", "The xHCI driver (future)", "The UART driver", "The PS/2 driver",
 "The keyboard driver", "The mouse driver", "The VBE driver", "The HPET driver", "The PIT driver",
 "The RTC driver", "The CMOS driver", "The SMBIOS reader", "The ACPI parser", "The IOMMU (the cmd)",
 "The SMP (the cmd)", "The GPU (future)", "The audio (future)", "The network (future)", "The NVMe (future)",
 "The driver registration", "The driver matching", "The driver init order", "The driver error paths",
 "The driver power (future)", "The driver tests", "The driver fuzz", "The driver bench", "The driver energy",
], "probe/remove -> the AHCI/xHCI -> the console-gated IOMMU/SMP"),
("KR-I", "The hosted & the metal duality", [
 "The hosted layer (the scaffold)", "The metal layer (the target)", "The PARITY project", "The dual paths",
 "The make runtime", "The make hosted", "The make check", "The metal boot verify", "The hosted tests",
 "The kernel build", "The docs build", "The ledger lint", "The 18 curated tests", "The full gate",
 "The parity matrix", "The host bridge", "The VSL on Linux", "The VSL on Windows (future)", "The VSL on macOS (future)",
 "The Wayland host", "The VBE host", "The input host", "The audio host (future)", "The GPU host",
 "The container host", "The 9P host", "The duality tests", "The duality bench", "The duality energy",
], "the hosted scaffold -> the metal target -> the parity matrix"),
("KR-J", "The kernel avenue engineering", [
 "The module registry", "The test matrix", "The boot tests", "The metal probes", "The QEMU harness",
 "The serial discipline", "The klog format limits", "The ISR gating", "The energy accounting",
 "The telemetry", "The watchdog", "The docs spec", "The roadmap", "The cross-link to the FS",
 "The cross-link to the network", "The cross-link to the AGI", "The cross-link to the Colonel",
 "The cross-link to the GUI", "The cross-link to the synthesis", "The milestones",
], "the engineering discipline for the kernel avenue"),
]

AIE = [
("AIE-A", "The serving core (batching)", [
 "The continuous batching (Orca)", "The iteration-level scheduling", "The static batching (the baseline)", "The dynamic batching",
 "The request queue", "The running set", "The swapped set", "The waiting set", "The preemption (the swap)", "The recompute",
 "The chunked prefill", "The prefix caching", "The prompt caching", "The beam caching", "The radix cache",
 "The max-num-seqs", "The gpu-memory-utilization", "The batch composition", "The token budget", "The scheduler policy",
 "The FCFS", "The shortest-remaining", "The priority classes", "The starvation guard", "The fairness",
 "The backpressure", "The overload policy", "The queue depth", "The latency SLO", "The throughput target",
 "The batching tests", "The batching bench", "The batching fuzz", "The batching energy",
], "Orca -> vLLM -> PagedAttention -> chunked prefill"),
("AIE-B", "The KV cache engine", [
 "The PagedAttention", "The KV blocks", "The block allocator", "The block table", "The block eviction",
 "The copy-on-write blocks", "The fork (the beam)", "The append", "The lookup", "The free-list",
 "The fragmentation (the solved)", "The pre-allocation", "The watermark", "The swap to CPU", "The swap to disk",
 "The KV compression (the theme IO)", "The KV quant (the theme B)", "The sink tokens (the theme IO)", "The head-adaptive (the IO)", "The eviction policies (the IO)",
 "The multi-query (the MQA)", "The grouped-query (the GQA)", "The sliding window", "The local attention", "The sparse attention",
 "The cache tests", "The cache bench", "The cache fuzz", "The cache energy",
], "PagedAttention -> GQA -> the IO-theme eviction frontier -> the tiers"),
("AIE-C", "The prefill & decode", [
 "The prefill phase", "The decode phase", "The fused prefill", "The split prefill (the future)", "The decode the token-by-token",
 "The speculative decoding (the theme)", "The draft model", "The verify batch", "The acceptance rate", "The break-even (the IJ)",
 "The self-speculation (the future)", "The n-gram drafts (the future)", "The prompt lookups (the future)", "The multi-token predict", "The Medusa (the future)",
 "The flash attention (the kernel)", "The flash decode", "The flash prefill", "The attention tiling", "The online softmax",
 "The causal mask (the fused)", "The head dims", "The sequence parallel (the future)", "The tensor parallel (the future)", "The pipeline parallel (the future)",
 "The prefill tests", "The prefill bench", "The prefill fuzz", "The prefill energy",
], "prefill/decode -> spec decode -> flash attention -> the parallels"),
("AIE-D", "The kernels & the compute", [
 "The GEMM", "The GEMV", "The matmul tiling", "The vectorized (the AVX2)", "The AVX512 (the hwdetect)",
 "The FMA", "The BF16 (the future)", "The FP16 (the future)", "The INT8 (the future)", "The INT4 (the future)",
 "The SIMD dispatch (the tier)", "The scalar fallback", "The multi-thread (the OMP-ish)", "The work partition", "The false sharing",
 "The cache blocking", "The register blocking", "The unrolling", "The swizzling (the future)", "The SIMT (the future)",
 "The Vulkan compute", "The CUDA (the future)", "The PTX (the future)", "The metal (the future)", "The WebGPU (the future)",
 "The kernel tests", "The kernel bench", "The kernel fuzz", "The kernel energy",
], "GEMM/GEMV -> SIMD tiers -> Vulkan -> the future CUDA/metal"),
("AIE-E", "The model loading", [
 "The safetensors reader", "The GGUF reader (the future)", "The checkpoint loader", "The shard loader", "The mmap loader",
 "The lazy load", "The weight streaming (the wubuwizard)", "The expert paging (the SSD)", "The weight quant on load", "The dequant",
 "The layout transpose", "The memory budget", "The peak memory", "The workspace", "The scratch",
 "The model registry", "The model versions", "The model A/B", "The model rollback", "The model quarantine",
 "The loader tests", "The loader bench", "The loader fuzz", "The loader energy",
], "safetensors -> mmap -> the weight streaming -> the expert paging"),
("AIE-F", "The sampling & the decode loop", [
 "The logits", "The temperature", "The top-k", "The top-p", "The min-p", "The repetition penalty",
 "The frequency penalty", "The presence penalty", "The tail-free (the future)", "The typical (the future)", "The mirostat (the future)",
 "The greedy", "The beam search", "The sampling seed", "The RNG", "The deterministic",
 "The stop tokens", "The max tokens", "The eos handling", "The bos", "The special tokens",
 "The logit bias", "The JSON schema (the future)", "The grammar (the future)", "The token heal (the future)", "The banned tokens",
 "The decode loop", "The incremental decode", "The streaming output", "The abort", "The pause",
 "The sampling tests", "The sampling bench", "The sampling fuzz", "The sampling energy",
], "top-k/p -> penalties -> grammar constraints -> the streaming loop"),
("AIE-G", "The context & the memory window", [
 "The context window", "The position encoding (the RoPE)", "The ALiBi (the future)", "The scaling (the NTK)", "The YaRN (the future)",
 "The long context", "The context compaction (the theme)", "The summarization", "The key/query eviction (the IO)", "The attention sinks (the IO)",
 "The sliding contexts", "The ring buffer", "The segment switching", "The context restore", "The KV reload",
 "The working set", "The scratchpad", "The thought chains", "The plan memory", "The episodic memory",
 "The semantic memory (the theme)", "The procedural memory (the theme)", "The associative (the IP)", "The consolidation (the sleep)", "The rehearsal",
 "The context tests", "The context bench", "The context fuzz", "The context energy",
], "RoPE -> NTK scaling -> the IO eviction -> the memory themes (IP/BB)"),
("AIE-H", "The MoE & the big models", [
 "The expert routing", "The top-k experts", "The shared experts", "The load balancing (the aux-loss)", "The z-loss",
 "The expert parallelism (the future)", "The expert offload (the SSD)", "The expert cache (the hot)", "The routing cache", "The softmax routing",
 "The routing-free MoE (the theme IZ)", "The PathMoE (the theme IZ)", "The deepseek balancing (the IZ)", "The capacity factor", "The token dropping",
 "The MoE tests", "The MoE bench", "The MoE fuzz", "The MoE energy",
], "top-k routing -> aux-loss balancing -> the IZ frontier -> the SSD offload"),
("AIE-I", "The serving topology", [
 "The single-model", "The multi-model", "The model multiplexing", "The per-request model", "The routing (the load)", "The affinity",
 "The preemption the model", "The model swap", "The warm pool", "The cold start", "The model warming",
 "The API (the OpenAI-ish)", "The streaming API", "The batch API", "The embeddings API", "The rerank (the future)",
 "The token counting", "The usage tracking", "The rate limits", "The API keys", "The auth",
 "The serving tests", "The serving bench", "The serving fuzz", "The serving energy",
], "single -> multi-model -> the API layer -> the usage/limits"),
("AIE-J", "The engine avenue engineering", [
 "The module registry", "The test matrix", "The bench harness", "The energy accounting", "The telemetry",
 "The watchdog", "The quantization QA", "The determinism", "The cross-model parity", "The docs spec",
 "The roadmap", "The cross-link to the wubuwizard", "The cross-link to the KV", "The cross-link to the energy",
 "The cross-link to the hwdetect", "The cross-link to the kernel", "The cross-link to the GUI", "The milestones",
], "the engineering discipline for the engine avenue"),
]

HX = [
("HX-A", "The user model", [
 "The user profile", "The preferences", "The tastes", "The habits", "The patterns",
 "The skill level", "The pace", "The fatigue", "The mood", "The context",
 "The session state", "The continuity", "The long-term memory", "The recall", "The forgetting curve",
 "The preference learning", "The implicit signals", "The explicit ratings", "The A/B", "The drift detection",
 "The privacy (the local)", "The export", "The deletion", "The consent", "The audit",
 "The user model tests", "The user model bench", "The user model fuzz", "The user model energy",
], "the user profile -> the implicit learning -> the privacy-first"),
("HX-B", "The adaptive UI (AUI)", [
 "The adaptive layout", "The adaptive theme", "The adaptive font", "The adaptive density", "The adaptive complexity",
 "The novice mode", "The expert mode", "The progressive disclosure", "The contextual menus", "The contextual help",
 "The adaptive shortcuts", "The adaptive defaults", "The workload adaptation", "The context adaptation", "The ability adaptation",
 "The legibility (the AUI rule)", "The reversibility (the AUI rule)", "The fairness (the AUI rule)", "The transparency", "The user control",
 "The adaptation logs", "The adaptation tests", "The adaptation bench", "The adaptation fuzz", "The adaptation energy",
], "AUI research -> legible/reversible/fair -> the adaptive OS"),
("HX-C", "The learning & the education", [
 "The tutor", "The mentor", "The coach", "The guide", "The explainer",
 "The Socratic mode", "The step-by-step", "The worked examples", "The practice", "The spaced repetition",
 "The flashcards", "The quizzes", "The assessments", "The progress tracking", "The mastery",
 "The curriculum", "The prerequisites", "The remediation", "The enrichment", "The pacing",
 "The teach-the-teacher", "The learning styles (the future)", "The gamification", "The badges", "The streaks",
 "The learning tests", "The learning bench", "The learning fuzz", "The learning energy",
], "the tutor -> spaced repetition -> mastery learning"),
("HX-D", "The companion (the Bonzi human side)", [
 "The empathy", "The warmth", "The humor", "The playfulness", "The personality",
 "The consistency", "The honesty", "The calibration", "The boundaries", "The consent",
 "The loneliness support", "The encouragement", "The celebration", "The commiseration", "The presence",
 "The idle chat", "The small talk", "The stories", "The jokes", "The riddles",
 "The memories shared", "The rituals", "The greetings", "The farewells", "The check-ins",
 "The companion tests", "The companion bench", "The companion fuzz", "The companion energy",
], "the JE-theme engine -> the empathy/calibration -> the presence"),
("HX-E", "The voice & the speech", [
 "The TTS (the voice)", "The STT (the listening)", "The prosody", "The emotion in voice", "The pacing",
 "The SSML-ish (the future)", "The voice identity", "The voice cloning (the future)", "The accents", "The languages",
 "The voice commands", "The wake word", "The barge-in", "The noise handling", "The echo cancel (the future)",
 "The captions", "The live transcription", "The speaker diarization (the future)", "The voice settings", "The voice privacy",
 "The voice tests", "The voice bench", "The voice fuzz", "The voice energy",
], "TTS/STT -> prosody -> the voice identity -> the privacy"),
("HX-F", "The games & the play", [
 "The chess", "The minesweeper", "The solitaire", "The snake", "The tetris (the future)",
 "The sudoku", "The word games", "The trivia", "The puzzles", "The memory games",
 "The learning games", "The serious games", "The party games (the future)", "The multiplayer (the future)", "The leaderboards",
 "The achievements", "The challenges", "The daily quests", "The streaks", "The scores",
 "The game engine (the simple)", "The game loop", "The input", "The audio (the synthesis)", "The themes",
 "The games tests", "The games bench", "The games fuzz", "The games energy",
], "the classics -> the learning games -> the achievements"),
("HX-G", "The art & the creation", [
 "The canvas app", "The brushes", "The layers (the future)", "The shapes", "The text",
 "The colors", "The palettes", "The filters (the future)", "The undo history", "The export",
 "The music (the synthesis)", "The composition (the seq)", "The wavetable editor", "The patch designer", "The mix",
 "The writing (the notes)", "The structuring (the outline)", "The ideas (the ideation)", "The mind-maps (the future)", "The poetry (the future)",
 "The photography (the future)", "The video (the future)", "The 3D (the future)", "The generative art (the future)", "The ASCII art",
 "The creation tests", "The creation bench", "The creation fuzz", "The creation energy",
], "the canvas -> the synthesis -> the generative future"),
("HX-H", "The accessibility & the inclusion", [
 "The screen reader", "The high contrast", "The large fonts", "The motion reduction", "The captions",
 "The voice control", "The switch access", "The keyboard nav", "The focus visible", "The error clarity",
 "The plain language", "The translations (the future)", "The localization (the future)", "The RTL (the future)", "The color-blind",
 "The seizure-safe (the future)", "The dyslexia-friendly (the future)", "The motor-friendly (the future)", "The hearing-friendly", "The vision-friendly",
 "The audit", "The tests", "The user feedback", "The iteration", "The energy",
], "the WCAG-ish -> the audit -> the inclusive default"),
("HX-I", "The wellbeing & the healthy", [
 "The focus timer", "The breaks", "The reminders", "The posture (the future)", "The screen time",
 "The blue light", "The bedtime", "The morning routine", "The evening routine", "The journaling",
 "The gratitude (the future)", "The breathing (the future)", "The meditation (the future)", "The mood check-ins", "The trends",
 "The gentle nudges", "The celebrating wins", "The supportive tone", "The no-shame design", "The user control",
 "The wellbeing tests", "The wellbeing bench", "The wellbeing fuzz", "The wellbeing energy",
], "the focus/breaks -> the journaling -> the no-shame design"),
("HX-J", "The human avenue engineering", [
 "The module registry", "The test matrix", "The A/B harness", "The energy accounting", "The telemetry",
 "The privacy audit", "The consent flows", "The docs spec", "The roadmap", "The cross-link to the GUI",
 "The cross-link to the Bonzi", "The cross-link to the AGI", "The cross-link to the synthesis", "The cross-link to the wubuwizard",
 "The cross-link to the compendium", "The milestones",
], "the engineering discipline for the human avenue"),
]

bank("docs/compendium/04-roadmap/network-bank.md", "Network Bank -- 1000 goals + gaps", NW)
bank("docs/compendium/04-roadmap/kernel-bank.md", "Kernel Bank -- 1000 goals + gaps (the metal)", KR)
bank("docs/compendium/04-roadmap/engine-bank.md", "AI-Engine Bank -- 1000 goals + gaps (the serving core)", AIE)
bank("docs/compendium/04-roadmap/human-bank.md", "Human Bank -- 1000 goals + gaps (the user's world)", HX)
print("all cores written")
