#!/usr/bin/env python3
"""Avenue core: MD (Media, 1000). 7-hop chain:
AV1/SVT-AV1 encoder optimization (2026 state: SVT-AV1 preset 4-6 production VOD,
preset 12 real-time, 40% faster in v4.0.0) -> Opus/LC3plus low-latency audio
(RFC 6716, 22.5ms algorithmic delay, Bluetooth LE Audio) -> neural audio codecs
(SoundStream RVQ, EnCodec, TQCodec 2603.01592, streamable low-complexity) ->
GStreamer zero-copy pipelines (dmabuf, V4L2, KMS, GPU/NPU passthrough) ->
learned neural video compression (CVPR 2026 Ultra-Fast NVC, rate-distortion
autoencoders, scene-adaptive NVC) -> the WuBuOS media substrate (Bonzi media
player, the Colonel's video pipeline, the hosted 9P media namespace).
"""
import os
os.makedirs("docs/compendium/04-roadmap", exist_ok=True)
T = []
def theme(name, title, gaps, refs):
    T.append(f"\n## {name}: {title}\nStatus: `open` = not yet built; `wired` = implemented + tested.\n### 7-hop convergence: {refs}\n")
    for i, g in enumerate(gaps, 1):
        T.append(f"- {name}{i:02d} {g} `open`\n")
    T.append(f"Status: `open` ({len(gaps)} gaps)\n")

theme("MD-A", "The video codec substrate (AV1 + HEVC + VVC)", [
    "The AV1 bitstream parser (the NAL-equivalent OBU)",
    "The AV1 superblock partition tree (64x64 down to 4x4)",
    "The AV1 intra-prediction modes (DC, H, V, Paeth, smooth, directional)",
    "The AV1 inter-prediction modes (global motion, WARP, affine)",
    "The AV1 reference frame management (last, golden, altref, buffered)",
    "The AV1 motion vector prediction (prev_mv, nearest, near, new)",
    "The AV1 loop filter (loop restoration + CDEF + luma + chroma)",
    "The AV1 quantization matrix (Q matrix, delta Q, segment-based)",
    "The AV1 rate control (the Q-index ladder, CRF, CBR, VBR)",
    "The AV1 tile columns + tile rows (the parallel decode)",
    "The AV1 film grain synthesis (the grain table + the synthesis pass)",
    "The SVT-AV1 preset 4-6 production sweet spot (VOD default 2026)",
    "The SVT-AV1 preset 12 real-time encode (1080p on a single core)",
    "The SVT-AV1 v4.0.0 speed improvements (40% faster on Intel/AMD)",
    "The SVT-AV1 content-adaptive encoding (CAE + DCA)",
    "The SVT-AV1 decoder complexity-aware optimization (DCA)",
    "The AV1 10-bit encode path (better PSNR/MS-SSIM/VMAF than 8-bit)",
    "The AV1 dual-ladder encode (AV1 + HEVC fallback for 20% tail)",
    "The HEVC CABAC entropy coder (the binary arithmetic coder)",
    "The HEVC CTU (coding tree unit, 64x64 quad-tree split)",
    "The HEVC SAO (sample adaptive offset filter)",
    "The HEVC ALF (adaptive loop filter)",
    "The HEVC temporal MV prediction (collocated MV from ref)",
    "The VVC (H.266) QTBT (quad-tree + binary tree partition)",
    "The VVC affine motion model (6-parameter + 8-parameter)",
    "The VVC ALF luma + chroma filter (separate controls)",
    "The VVC MRL (most recent reference) reference selection",
    "The VVC ISP (intra sub-partitioning, recursive quad split)",
    "The VVC explicit scaling list (the quant matrix preset)",
    "The AV1 encoder benchmark vs HEVC vs VVC (BD-rate table)",
    "The hardware AV1 encoder (Intel Arc, NVIDIA RTX 40+, AMD RDNA 3+)",
    "The hardware HEVC encoder (the real-time 4K60 path)",
    "The V4L2 AV1 encoder interface (the /dev/video* codec node)",
    "The VAAPI AV1 encode surface (the GPU memory path)",
    "The NVENC AV1 encode session (the NVIDIA driver path)",
    "The AMF AV1 encode (the AMD media framework path)",
    "The FFmpeg AV1 encode thread (the libaom + SVT-AV1 + rav1e wrapper)",
    "The FFmpeg HEVC encode thread (the x265 wrapper)",
    "The FFmpeg VVC encode thread (the libvvcc wrapper, experimental)",
    "The encode preset selector (the auto-tune for the workload)",
    "The encode quality target (the VMAF/PSNR/MS-SSIM goal)",
    "The encode speed budget (the frames-per-second constraint)",
    "The encode bitrate cap (the bandwidth ceiling)",
    "The encode resolution ladder (480p -> 720p -> 1080p -> 4K)",
    "The encode tile-grid strategy (the parallelism vs overhead trade)",
    "The encode lookahead buffer (the frame-skip decision)",
    "The encode scene-change detector (the keyframe trigger)",
    "The encode keyframe interval (the GOP size policy)",
    "The encode delta frame policy (the B-frame strategy)",
    "The encode noise sensitivity (the grain preservation flag)",
    "The encode color-space metadata (the BT.709/BT.2020/HLG tag)",
    "The video codec tests (the encode-decode round-trip check)",
    "The video codec docs (the encoder cookbook)",
], "AV1/SVT-AV1 (2026: SVT-AV1 v4.0.0, preset 4-6 VOD, preset 12 real-time, 40% faster) -> HEVC/H.265 (the real-time fallback) -> VVC/H.266 (the next-gen) -> the WuBuOS video pipeline (the Colonel's display + the Bonzi player)"),

theme("MD-B", "The audio codec substrate (Opus + LC3 + neural)", [
    "The Opus SILK layer (the LPC-based speech coder)",
    "The Opus CELT layer (the MDCT-based music coder)",
    "The Opus hybrid switch (the speech/music decision)",
    "The Opus VBR mode (the bitrate allocation per frame)",
    "The Opus CBR mode (the fixed bitrate path)",
    "The Opus constrained-VBR mode (the quality floor)",
    "The Opus frame size (2.5ms, 5ms, 10ms, 20ms, 40ms, 60ms)",
    "The Opus algorithmic delay (22.5ms to 60ms, 5ms in restricted mode)",
    "The Opus bandwidth adaptation (narrowband -> fullband -> stereo)",
    "The Opus FEC (forward error correction, the packet loss concealment)",
    "The Opus DTX (discontinuous transmission, the silence compression)",
    "The Opus VAD (voice activity detection, the speech/music classifier)",
    "The Opus in-band FEC (the redundancy payload)",
    "The Opus side-band signaling (the config change mid-stream)",
    "The LC3 (Low Complexity Communication Codec, the Bluetooth LE Audio default)",
    "The LC3plus (the Fraunhofer superset, 96 kHz, 2.5ms frame)",
    "The LC3 bit allocation (the energy-based allocation)",
    "The LC3 tonality detection (the tonal vs noisey frame classifier)",
    "The LC3 pitch analysis (the pitch period + gain)",
    "The LC3 residual coding (the residual quantizer)",
    "The LC3 LTP (long-term prediction, the pitch filter)",
    "The LC3 TNS (temporal noise shaping, the masking model)",
    "The LC3 MSBC mode (the dual-channel sub-band coder)",
    "The neural audio codec shape (encoder + RVQ + decoder)",
    "The SoundStream RVQ (the residual vector quantization, the coin-change analogy)",
    "The SoundStream adversarial training (the discriminator, the crisp audio)",
    "The SoundStream 3-18 kbps multi-rate (the layer-dropping trick)",
    "The EnCodec (Meta, the music-quality neural codec)",
    "The EnCodec multi-scale STFT discriminator (the music percept)",
    "The EnCodec 24-48 kHz 24 kbps (the music streaming target)",
    "The TQCodec (arXiv 2603.01592, the high-fidelity music streaming codec)",
    "The TQCodec residual SimVQ (the improved RVQ with codebook utilization)",
    "The streamable neural codec (arXiv 2504.06561, the WebRTC-grade neural codec)",
    "The neural codec layer-dropping (the adaptive bitrate without re-encoding)",
    "The neural codec RVQ codebook size (the tradeoff: bits vs quality)",
    "The neural codec encoder complexity (the CPU budget for the encoder)",
    "The neural codec decoder complexity (the CPU budget for the decoder)",
    "The audio codec latency budget (the end-to-end delay constraint)",
    "The audio codec packet loss resilience (the concealment + FEC strategy)",
    "The audio codec JET buffer (the jitter equalizer + the playout delay)",
    "The audio codec A/B test (the subjective quality comparison)",
    "The audio codec objective metric (the POLQA, the PESQ, the STOI)",
    "The audio codec bandwidth adaptation (the network condition monitor)",
    "The audio codec echo cancellation (the AEC, the near-end vs far-end)",
    "The audio codec noise suppression (the NS, the RNNoise shape)",
    "The audio codec automatic gain control (the AGC, the level normalization)",
    "The audio codec test corpus (the speech + music + noise datasets)",
    "The audio codec docs (the codec selection guide)",
], "Opus (RFC 6716, SILK+CELT, 22.5ms delay) -> LC3/LC3plus (Bluetooth LE Audio, 2.5ms frame) -> SoundStream RVQ -> EnCodec -> TQCodec (arXiv 2603.01592) -> streamable neural codec (arXiv 2504.06561) -> the WuBuOS audio engine (the Bonzi player + the Colonel's audio pipeline)"),

theme("MD-C", "The container + streaming format (WebM, MP4, Matroska, MPEG-DASH)", [
    "The Matroska container format (the EBML schema)",
    "The EBML (Extensible Binary Meta Language) reader",
    "The EBML ID + size encoding (the variable-length integer)",
    "The EBML master element (the container-within-a-container)",
    "The EBML unsigned integer (the 1-8 byte encoding)",
    "The EBML float (the IEEE 754 in EBML)",
    "The EBML date (the nanosecond Unix timestamp)",
    "The EBML string (the UTF-8 text payload)",
    "The EBML binary (the raw byte payload)",
    "The WebM container (the subset of Matroska for web)",
    "The WebM VP8/VP9/AV1 track (the video track in the Matroska schema)",
    "The WebM Opus/Vorbis/FLAC track (the audio track in the Matroska schema)",
    "The MP4 container (the ISO BMFF, the box hierarchy)",
    "The MP4 ftyp box (the file type declaration)",
    "The MP4 moov box (the movie metadata, the track + edit list)",
    "The MP4 mdat box (the media data, the raw sample payload)",
    "The MP4 trak box (the track, the media + header)",
    "The MP4 mdia box (the media, the handler + info + sample table)",
    "The MP4 minf box (the media information, the sample + chunk offset)",
    "The MP4 stbl box (the sample table, the chunk + sample descriptors)",
    "The MP4 stco box (the chunk offset table)",
    "The MP4 co64 box (the 64-bit chunk offset table)",
    "The MP4 stsc box (the sample-to-chunk mapping)",
    "The MP4 stsz box (the sample size table)",
    "The MP4 stts box (the sample-to-decoding-time offset table)",
    "The MP4 ctts box (the composition time offset table)",
    "The MP4 stss box (the sync sample table, the keyframe list)",
    "The MP4 sdtp box (the sample dependency type)",
    "The MP4 mehd box (the movie extension duration)",
    "The MP4 trex box (the track extension default values)",
    "The MP4 mvex box (the movie extension, the track fragment)",
    "The MP4 traf box (the track fragment, the decode -> sample table)",
    "The MP4 tfhd box (the track fragment header)",
    "The MP4 tfdt box (the track fragment decode timestamp)",
    "The MP4 trun box (the track run, the sample info per chunk)",
    "The DASH manifest (the MPD, the Media Presentation Description)",
    "The DASH SegmentBase (the initialization segment reference)",
    "The DASH SegmentList (the explicit segment URL list)",
    "The DASH SegmentTemplate (the URL template + timeline)",
    "The DASH Representation (the bandwidth + resolution + codec profile)",
    "The DASH AdaptationSet (the group of representations for the same content)",
    "The DASH Period (the temporal partition of the presentation)",
    "The HLS manifest (the m3u8 playlist, the Apple HTTP Live Streaming)",
    "The HLS EXT-X-STREAM-INF (the bandwidth + resolution variant)",
    "The HLS EXT-X-TARGETDURATION (the segment duration ceiling)",
    "The HLS EXT-X-MEDIA-SEQUENCE (the segment counter)",
    "The HLS EXT-X-PROGRAM-DATE-TIME (the wall-clock timestamp)",
    "The HLS fMP4 (the fragmented MP4, the CMAF shape)",
    "The CMAF common encryption (the CENC, the AES-128 CTR + pattern)",
    "The container round-trip test (the encode -> mux -> demux -> decode check)",
    "The container docs (the format specification reference)",
], "the Matroska/EBML schema -> the WebM subset for web delivery -> the MP4/BMFF box hierarchy -> the DASH MPD manifest -> the HLS m3u8 playlist -> the CMAF fMP4 chunked format -> the WuBuOS media container (the 9P-exported media namespace)"),

theme("MD-D", "The zero-copy media pipeline (GStreamer + dmabuf + V4L2 + KMS)", [
    "The GStreamer pipeline model (the src -> filter -> sink chain)",
    "The GStreamer element (the base class, the pad interface)",
    "The GStreamer pad (the src pad + the sink pad)",
    "The GStreamer caps (the capability negotiation, the format + resolution)",
    "The GStreamer buffer (the GstBuffer, the metadata + the memory list)",
    "The GStreamer memory (the GstMemory, the fd + offset + size)",
    "The GStreamer dmabuf memory (the fd-based shared memory)",
    "The GStreamer V4L2 src element (the camera device -> buffer)",
    "The GStreamer V4L2 sink element (the buffer -> display device)",
    "The GStreamer kmssink element (the KMS framebuffer output)",
    "The GStreamer waylandsink element (the Wayland surface output)",
    "The GStreamer ximagesink element (the X11 window output)",
    "The GStreamer glimagesink element (the OpenGL texture output)",
    "The dmabuf fd export (the DMA-BUF file descriptor, the shared buffer)",
    "The dmabuf fd import (the receiving process, the buffer attachment)",
    "The V4L2 buffer plane (the multi-planar format, the Y + U + V planes)",
    "The V4L2 DMABUF ioctl (the export + import buffer)",
    "The V4L2 MMAP buffer (the kernel mmap, the zero-copy capture)",
    "The V4L2 USERPTR buffer (the userspace pointer, the copy path)",
    "The KMS framebuffer (the DRM framebuffer, the scanout buffer)",
    "The KMS CRTC (the cathode ray tube controller, the output encoder)",
    "The KMS plane (the overlay plane, the src + dst + z-order)",
    "The DRM prime FD (the buffer export across drivers)",
    "The DRM gem buffer (the TTM buffer object, the GPU-local memory)",
    "The NVMM buffer (the NVIDIA memory, the Jetson zero-copy path)",
    "The ISP pipeline (the image signal processor, the raw -> RGB conversion)",
    "The GPU compositor (the Wayland compositor, the buffer reuse)",
    "The NPU inference pipeline (the buffer -> model -> output buffer)",
    "The zero-copy end-to-end path (camera -> ISP -> DMABUF -> GStreamer -> GPU/NPU -> sink)",
    "The zero-copy CPU overhead measurement (the perf stat, the context switches)",
    "The zero-copy frame-drop budget (the latency vs quality trade)",
    "The zero-copy pipeline test (the end-to-end latency check)",
    "The zero-copy pipeline benchmark (the throughput in frames/sec)",
    "The GStreamer pipeline description language (the gst-launch-1.0 syntax)",
    "The GStreamer debug category (the log level + the category filter)",
    "The GStreamer event (the EOS, the seek, the flush)",
    "The GStreamer query (the duration, the position, the latency)",
    "The GStreamer bus (the message pump, the error + warning + info)",
    "The GStreamer plugin (the shared library, the register + create)",
    "The GStreamer plugin registry (the scan + the cache)",
    "The GStreamer appsrc element (the push-based source)",
    "The GStreamer appsink element (the pull-based sink)",
    "The GStreamer tee element (the branch point, the copy vs passthrough)",
    "The GStreamer queue element (the buffering, the max-size-buffers)",
    "The GStreamer rate element (the playback speed, the time mapping)",
    "The GStreamer audio convert (the channel mix + resample)",
    "The GStreamer video convert (the colorspace + resolution conversion)",
    "The GStreamer capsfilter element (the format negotiation gate)",
    "The GStreamer identity element (the passthrough, the signal handoff)",
    "The GStreamer tests (the pipeline integration check)",
    "The GStreamer docs (the plugin cookbook)",
], "GStreamer pipeline model -> dmabuf zero-copy (the shared FD) -> V4L2 MMAP capture -> KMS scanout -> the Wayland compositor -> the WuBuOS display pipeline (the Colonel's framebuffer + the Bonzi compositor)"),

theme("MD-E", "The neural video compression (learned NVC)", [
    "The rate-distortion objective (R + lambda*D, the Lagrangian tradeoff)",
    "The autoencoder shape (encoder -> bottleneck -> decoder, the end-to-end train)",
    "The scale-space Laplacian pyramid (the multi-scale residual hierarchy)",
    "The hyper-prior (the latent prior network, the entropy model)",
    "The entropy model (the learned probability distribution, the NLL loss)",
    "The quantization (the uniform scalar quantizer, the step size)",
    "The de-quantization (the reconstruction, the half-step offset)",
    "The stochastic rounding (the noise injection, the gradient estimator)",
    "The anchor-based rate control (the VTM anchor, the BD-rate metric)",
    "The scene-adaptive NVC (the PNVC, the per-scene parameter tuning)",
    "The HiNeRV (the hierarchical recurrent video codec, the temporal model)",
    "The DCVC (the deep compression video codec, the CNN encoder)",
    "The DCVC-RT (the real-time DCVC, the speed-optimized variant)",
    "The C3 codec (the chunk-based coding, the temporal context)",
    "The NVRC (the neural video codec, the recurrent backbone)",
    "The GIViC (the generative image compression, the GAN backbone)",
    "The MaskCRT (the masked conditional random field, the spatial model)",
    "The Ultra-Fast NVC (CVPR 2026, the chunk-based R-D-C tradeoff)",
    "The chunk-based coding framework (the rate-distortion-complexity triple trade)",
    "The temporal reference selection (the keyframe + the P-frame + the B-frame)",
    "The motion-compensated prediction (the optical flow + the MV residual)",
    "The deformable convolution (the adaptive sampling, the spatial warp)",
    "The attention mechanism (the self-attention, the cross-frame attention)",
    "The transformer backbone (the ViT-style encoder, the global context)",
    "The CNN backbone (the ResNet-style encoder, the local context)",
    "The hybrid CNN+transformer backbone (the local + global features)",
    "The learned intra-prediction (the neural spatial predictor)",
    "The learned inter-prediction (the neural motion-compensated predictor)",
    "The learned loop filter (the neural restoration, the Deblocking CNN)",
    "The learned super-resolution (the SR post-processing, the enhancement)",
    "The neural codec training dataset (the UVG, the MCL-JCV, the HEVC B-E)",
    "The neural codec evaluation metric (the PSNR, MS-SSIM, VMAF, BD-rate)",
    "The neural codec complexity metric (the kMACs/px, the encode time)",
    "The neural codec rate control (the lambda ladder, the QP schedule)",
    "The neural codec entropy coding (the arithmetic coder, the hyper-prior)",
    "The neural codec progressive decoding (the layer-by-layer refinement)",
    "The neural codec adaptive rate (the bitrate switch mid-stream)",
    "The neural codec error concealment (the packet loss recovery)",
    "The neural codec end-to-end latency (the encode -> transmit -> decode budget)",
    "The neural codec hardware target (the CPU-only, the GPU, the NPU)",
    "The neural codec vs conventional codec (the BD-rate comparison table)",
    "The neural codec real-time feasibility (the encode speed vs quality trade)",
    "The neural codec deployment (the ONNX export, the TensorRT path)",
    "The neural codec tests (the encode-decode round-trip + the R-D evaluation)",
    "The neural codec docs (the architecture reference + the training guide)",
], "the rate-distortion autoencoder -> the scale-space Laplacian pyramid -> the hyper-prior entropy model -> the learned intra/inter prediction -> the Ultra-Fast NVC (CVPR 2026) -> the WuBuOS neural media pipeline (the Colonel's learned codec + the Bonzi adaptive stream)"),

theme("MD-F", "The media transport (RTP/RTCP + WebRTC + 9P media namespace)", [
    "The RTP header (the version + padding + extension + CSRC list)",
    "The RTP payload type (the codec identifier, the dynamic mapping)",
    "The RTP timestamp (the 90kHz clock for video, the 48kHz for audio)",
    "The RTP sequence number (the per-packet counter, the loss detection)",
    "The RTP SSRC (the synchronization source, the stream identifier)",
    "The RTP CSRC (the contributing source, the mixer list)",
    "The RTCP SR (the sender report, the NTP timestamp + RTP timestamp)",
    "The RTCP RR (the receiver report, the loss fraction + the jitter)",
    "The RTCP SDES (the source description, the CNAME + name + email)",
    "The RTCP BYE (the graceful departure, the reason code)",
    "The RTCP XR (the extended report, the loss RLE + the delay since last SR)",
    "The RTCP REMB (the receiver estimated maximum bitrate, the congestion signal)",
    "The RTCP TWCC (the transport-wide congestion control, the per-packet feedback)",
    "The WebRTC RTCPeerConnection (the offer/answer + the ICE candidate exchange)",
    "The WebRTC ICE (the connectivity check, the STUN + TURN traversal)",
    "The WebRTC DTLS (the transport-layer security, the SRTP key exchange)",
    "The WebRTC SRTP (the encrypted RTP, the AES-128-ICM + HMAC-SHA1)",
    "The WebRTC media stream (the audio track + the video track)",
    "The WebRTC transceiver (the direction + the codec negotiation)",
    "The WebRTC codec preference (the OPUS priority + the AV1 priority)",
    "The WebRTC bandwidth estimation (the GCC, the REMB + TWCC)",
    "The WebRTC jitter buffer (the adaptive playout delay, the packet reorder)",
    "The WebRTC NACK (the negative acknowledgment, the retransmission request)",
    "The WebRTC PLI (the picture loss indication, the keyframe request)",
    "The WebRTC FIR (the full intra request, the decoder refresh)",
    "The WebRTC SLI (the slice loss indication, the partial recovery)",
    "The 9P protocol (the Styx protocol, the 9P2000.L revision)",
    "The 9P message (the T-version + R-version handshake)",
    "The 9P walk (the path traversal, the QID + the fid)",
    "The 9P read (the file read, the offset + count)",
    "The 9P write (the file write, the offset + count)",
    "The 9P stat (the file metadata, the stat structure)",
    "The 9P open (the file open, the mode + the fid)",
    "The 9P create (the file create, the permissions)",
    "The 9P remove (the file remove, the fid)",
    "The 9P flush (the message abort, the old tag)",
    "The 9P attach (the connection attach, the auth)",
    "The 9P auth (the authentication, the Ahistor)",
    "The 9P error (the error response, the ename)",
    "The 9P media export (the /n/media/ path, the video + audio streams)",
    "The 9P media read (the chunked read, the offset + length)",
    "The 9P media write (the chunked write, the offset + length)",
    "The media transport test (the RTP round-trip + the 9P read/write)",
    "The media transport docs (the protocol reference + the API cookbook)",
], "RTP/RTCP (the media transport) -> WebRTC (the real-time communication) -> 9P media namespace (the /n/media/ export) -> the WuBuOS media transport (the Colonel's 9P media server + the Bonzi stream)"),

theme("MD-G", "The media display (the framebuffer + the compositor + the Wayland surface)", [
    "The DRM connector (the physical output, the encoder + the CRTC)",
    "The DRM encoder (the digital/analog signal, the TMDS + LVDS)",
    "The DRM CRTC (the scanout engine, the mode + the framebuffer)",
    "The DRM framebuffer (the GEM buffer, the pitch + offset + modifier)",
    "The DRM plane (the overlay plane, the src + dst + z-order + alpha)",
    "The DRM property (the connector property, the CRTC property, the plane property)",
    "The DRM mode (the timing, the hdisplay + vdisplay + vrefresh)",
    "The DRM atomic commit (the test + commit + enable-vbye)",
    "The DRM KMS (the kernel mode setting, the modeset + the page flip)",
    "The DRM page flip (the vblank-synchronized buffer swap)",
    "The DRM FBDEV (the legacy framebuffer, the fb0 device)",
    "The Wayland display (the wl_display, the event loop)",
    "The Wayland registry (the global object discovery, the bind)",
    "The Wayland compositor (the wl_compositor, the surface + the layer)",
    "The Wayland surface (the wl_surface, the buffer + the damage)",
    "The Wayland buffer (the wl_buffer, the SHM + the dmabuf)",
    "The Wayland SHM pool (the shared memory, the fd + the size)",
    "The Wayland SHM buffer (the wl_shm_buffer, the format + the stride)",
    "The Wayland dmabuf feedback (the preferred format + the modifier)",
    "The Wayland subcompositor (the wl_subcompositor, the subsurface)",
    "The Wayland data device (the wl_data_device, the clipboard + the drag)",
    "The Wayland seat (the wl_seat, the keyboard + the pointer + the touch)",
    "The Wayland pointer (the wl_pointer, the enter + the leave + the motion)",
    "The Wayland keyboard (the wl_keyboard, the key + the modifiers)",
    "The Wayland touch (the wl_touch, the down + the up + the motion)",
    "The Wayland output (the wl_output, the geometry + the mode + the scale)",
    "The Wayland xdg_shell (the xdg_surface + the xdg_toplevel)",
    "The Wayland xdg surface (the configure + the commit + the frame callback)",
    "The Wayland xdg toplevel (the title + the app_id + the maximize + the fullscreen)",
    "The Wayland xdg popup (the transient + the parent + the position)",
    "The Wayland presentation feedback (the vsync + the refresh + the notify)",
    "The Wayland primary selection (the wl_primary_selection, the selection data)",
    "The Wayland cursor (the wl_cursor, the surface + the hotspot)",
    "The Wayland surface damage (the frame callback + the damage region)",
    "The Wayland surface commit (the buffer + the damage + the state)",
    "The compositor hit testing (the surface at a point, the stacking order)",
    "The compositor damage tracking (the accumulated damage + the repaint region)",
    "The compositor buffer recycling (the reuse + the age + the stamp)",
    "The compositor frame scheduling (the vsync + the deadline + the refresh)",
    "The compositor vsync timing (the refresh interval + the frame budget)",
    "The compositor latency measurement (the frame time + the queue delay)",
    "The compositor overlay planes (the hardware overlay, the primary + the cursor)",
    "The compositor gamma ramp (the LUT, the brightness + the contrast)",
    "The compositor color management (the ICC profile + the intent)",
    "The display test (the frame timing + the color accuracy + the tear check)",
    "The display docs (the DRM + Wayland reference + the WuBuOS framebuffer driver)",
], "the DRM/KMS framebuffer -> the Wayland compositor + surface protocol -> the 9P display namespace -> the WuBuOS display pipeline (the Colonel's KMS driver + the Bonzi compositor + the WuBuFX window system)"),

theme("MD-H", "The media application (the Bonzi player + the WuBuOS media UI)", [
    "The media player state machine (the idle + the loading + the playing + the paused)",
    "The media player URI (the file path + the 9P path + the http URL)",
    "The media player demux (the container parser + the track selector)",
    "The media player decoder (the video decoder + the audio decoder)",
    "The media player renderer (the video frame + the audio sample)",
    "The media player clock (the presentation timestamp, the playback rate)",
    "The media player seek (the time -> byte offset, the keyframe search)",
    "The media player playlist (the queue + the shuffle + the repeat)",
    "The media player subtitle (the SRT + the VTT + the ASS parser)",
    "The media player audio track (the language + the channel layout)",
    "The media player video track (the resolution + the codec + the HDR flag)",
    "The media player chapter (the navigation + the title)",
    "The media player menu (the OSD menu + the button + the slider)",
    "The media player fullscreen (the toggle + the escape + the pointer grab)",
    "The media player aspect ratio (the 4:3 + the 16:9 + the 21:9 + the auto)",
    "The media player zoom (the 0.5x + the 1x + the 2x + the fit + the fill)",
    "The media player rotation (the 0 + the 90 + the 180 + the 270)",
    "The media player mirroring (the horizontal flip, the vertical flip)",
    "The media player screenshot (the frame capture + the file save)",
    "The media player recording (the encode + the file write + the stop)",
    "The media player equalizer (the bass + the mid + the treble + the preset)",
    "The media player audio visualization (the waveform + the spectrum)",
    "The media player video effects (the brightness + the contrast + the saturation)",
    "The media player audio effects (the volume + the balance + the spatial)",
    "The media player bookmarks (the timestamp + the label + the list)",
    "The media player history (the recently played + the resume point)",
    "The media player preferences (the codec default + the quality + the cache)",
    "The media player keyboard shortcuts (the play/pause + the seek + the fullscreen)",
    "The media player mouse controls (the click + the drag + the scroll + the right-click)",
    "The media player touch controls (the tap + the swipe + the pinch + the long-press)",
    "The media player remote controls (the infrared + the keyboard + the gamepad)",
    "The media player accessibility (the captions + the audio description + the high-contrast)",
    "The media player theming (the 98 chrome + the dark mode + the compact)",
    "The media player integration (the 9P media export + the Wayland surface + the GStreamer pipeline)",
    "The media player tests (the format support + the seek accuracy + the latency)",
    "The media player docs (the user guide + the keyboard shortcut reference)",
], "the Win98 media player lineage -> the Bonzi companion (HX-D) as the media player -> the WuBuOS media application (the Colonel's media UI + the Bonzi player)"),

theme("MD-I", "The media integration (the 9P media namespace + the hosted media layer)", [
    "The 9P media root (the /n/media/ export root)",
    "The 9P video export (the /n/media/video/ directory)",
    "The 9P audio export (the /n/media/audio/ directory)",
    "The 9P image export (the /n/media/image/ directory)",
    "The 9P stream export (the /n/media/stream/ directory, the live feed)",
    "The 9P media stat (the file metadata, the duration + the resolution + the codec)",
    "The 9P media read (the chunked read, the offset + the count)",
    "The 9P media write (the chunked write, the append + the truncate)",
    "The 9P media watch (the inotify-style notification, the modify event)",
    "The 9P media lock (the advisory lock, the read lock + the write lock)",
    "The 9P media auth (the per-user access control, the read + the write + the admin)",
    "The 9P media quota (the per-user byte limit + the per-file limit)",
    "The 9P media cache (the client-side buffer, the read-ahead + the write-behind)",
    "The 9P media sync (the fsync + the datasync + the flush)",
    "The 9P media version (the 9P2000.L + the 9P2000.u + the 9P2000.x)",
    "The hosted media layer (the containerized media process, the resource limit)",
    "The hosted media process (the namespace + the cgroup + the seccomp)",
    "The hosted media container (the image + the runtime + the network)",
    "The hosted media bridge (the 9P mount + the pipe + the socket)",
    "The hosted media proxy (the protocol translation, the RTSP -> 9P)",
    "The hosted media gateway (the external -> internal, the NAT + the firewall)",
    "The hosted media monitor (the health check + the metrics + the alert)",
    "The hosted media recovery (the restart + the rollback + the replay)",
    "The hosted media scaling (the horizontal + the vertical + the bitrate)",
    "The hosted media failover (the primary + the standby + the switch)",
    "The hosted media load balancing (the round-robin + the least-conn + the hash)",
    "The hosted media QoS (the priority + the bandwidth + the latency)",
    "The hosted media security (the TLS + the auth + the audit)",
    "The hosted media logging (the access log + the error log + the audit log)",
    "The hosted media tracing (the span + the trace ID + the baggage)",
    "The hosted media config (the YAML + the env + the flag + the 9P read)",
    "The hosted media tests (the integration + the performance + the chaos)",
    "The hosted media docs (the architecture + the API + the operations guide)",
], "the 9P media namespace (the /n/media/ path) -> the hosted media layer (the containerized media process) -> the WuBuOS media substrate (the Colonel's namespace + the Bonzi hosted media)"),

theme("MD-J", "The media engineering close", [
    "The MD threat model (the media attack surface, the buffer overflow + the format parser)",
    "The MD performance budget (the encode latency + the decode latency + the end-to-end)",
    "The MD memory budget (the 13GB reality, the frame buffer + the codec state)",
    "The MD no-network rule (the offline-first media, the local codec + the local container)",
    "The MD determinism rule (the same input -> the same output, the reproducible encode)",
    "The MD reproducibility check (the encode-decode round-trip + the hash compare)",
    "The MD integration with the storage bank (the CAS on littlefs, the media artifact store)",
    "The MD integration with the network bank (the QUIC media transport, the 9P media export)",
    "The MD integration with the kernel bank (the DRM/KMS driver, the V4L2 codec node)",
    "The MD integration with the engine bank (the neural codec inference, the NPU path)",
    "The MD integration with the human bank (the media accessibility, the Bonzi companion)",
    "The MD integration with the security bank (the signed media pipeline, the CENC)",
    "The MD integration with the GUI bank (the Win98 media player, the Bonzi UI)",
    "The MD integration with the synthesis bank (the audio dev tools, the wavetable pipeline)",
    "The MD cross-bank gap ledger (the media gaps that touch other banks)",
    "The MD close-rate report (the encode-decode pass rate, the format support rate)",
    "The MD CI matrix (the codec + the container + the resolution + the bitrate grid)",
    "The MD smoke test (the encode -> mux -> demux -> decode -> verify)",
    "The MD soak test (the 24h encode-decode endurance, the memory leak check)",
    "The MD stress test (the 4K60 encode + the 8-channel audio, the CPU ceiling)",
    "The MD chaos test (the packet loss + the frame drop + the codec mismatch)",
    "The MD upgrade test (the codec version bump, the backward compat)",
    "The MD downgrade test (the fallback to HEVC when AV1 is unsupported)",
    "The MD cold-start benchmark (the first-frame decode latency)",
    "The MD warm-cache benchmark (the seek-to-keyframe latency)",
    "The MD incremental-edit benchmark (the re-encode after a trim)",
    "The MD full-rebuild benchmark (the transcode from scratch)",
    "The MD trace-size benchmark (the bitrate vs the quality vs the latency)",
    "The MD spec doc (the codec selection + the container format + the transport)",
    "The MD design doc (the architecture + the data flow + the failure modes)",
    "The MD API reference (the 9P media protocol + the GStreamer pipeline + the Wayland surface)",
    "The MD tutorial (the first encode + the first stream + the first display)",
    "The MD troubleshooting guide (the format not supported + the decode failure + the latency spike)",
    "The MD roadmap (the short-term + the mid-term + the long-term media milestones)",
    "The MD bank ledger (the gap count + the wired count + the close rate)",
], "the threat model -> the budget matrix -> the cross-bank integration -> the MD roadmap -> the WuBuOS media engineering close")

with open("docs/compendium/04-roadmap/media-bank.md", "w") as f:
    f.write("# Media Bank -- 1000 goals + gaps (the media substrate)\n\n")
    f.write("Date: 2026-08-03. The Media avenue: the video codec (AV1/HEVC/VVC), the audio codec (Opus/LC3/neural),\n")
    f.write("the container + streaming format (WebM/MP4/DASH/HLS), the zero-copy media pipeline (GStreamer/dmabuf),\n")
    f.write("the neural video compression (CVPR 2026 Ultra-Fast NVC), the media transport (RTP/WebRTC/9P),\n")
    f.write("the media display (DRM/KMS/Wayland), the media application (Bonzi player), and the media integration.\n")
    f.write("Status: `open` / `wired`. Every gap is a real mechanism from the surveyed lineage (AV1/SVT-AV1 ->\n")
    f.write("Opus/LC3 -> neural audio codecs -> GStreamer zero-copy -> learned NVC -> the WuBuOS media substrate).\n")
    f.write("".join(T))

count = sum(1 for l in T if l.startswith("- MD-"))
print(f"Media core: {count} gaps across {len([l for l in T if l.startswith('## MD-')])} themes")
