#!/usr/bin/env python3
"""Avenue banks part 1: FS (storage, 1000) + NW (network, 1000)."""
import os
os.makedirs("docs/compendium/04-roadmap", exist_ok=True)
T = []
def theme(name, title, gaps, refs):
    T.append(f"\n## {name}: {title}\nStatus: `open` = not yet built; `wired` = implemented + tested.\n### 7-hop convergence: {refs}\n")
    for i, g in enumerate(gaps, 1):
        T.append(f"- {name}{i:02d} {g} `open`\n")
    T.append(f"Status: `open` ({len(gaps)} gaps)\n")

theme("FS-A", "The block layer & media", [
 "Block device abstraction (the 9P /dev/block)",
 "Sector read/write (the AHCI adapter)",
 "Sector count convention (the ahci returns-count rule)",
 "Block cache (the LRU)",
 "Block prefetch (the sequential)",
 "Block flush (the ordered)",
 "Block barriers (the ordering)",
 "Trim/discard (the flash)",
 "Wear leveling (the flash blocks)",
 "Bad block management",
 "Partition table (the MBR/GPT)",
 "Partition mounting",
 "Sector remapping (the bad-sector)",
 "Read-ahead window (the adaptive)",
 "Write-back caching (the policies)",
 "Write-through mode",
 "O_DIRECT (the bypass)",
 "Block queue (the merged)",
 "Block priority (the QoS)",
 "Block energy (the IJ ledger)",
 "Block benchmarks (the MB/s)",
 "Block fuzz (the sector corruption)",
 "Block tests (the roundtrip)",
 "NVMe support (the future)",
 "AHCI port enumeration (the metal)",
 "SATA vs virtio (the hosted)",
 "RAM disk (the wubu_ramdisk)",
 "Loop device (the image file)",
 "Device mapper (the stacking)",
 "RAID-0 (the stripe)",
 "RAID-1 (the mirror)",
 "RAID-5 (the parity)",
 "RAID-10",
 "Snapshot blocks (the CoW)",
 "Block dedup (the hash)",
 "Block compression (the zstd)",
 "Block encryption (the AES)",
 "Block checksums (the end-to-end)",
 "Block journal (the intent log)",
 "Block recovery (the crash)",
 "Block hotplug (the USB)",
 "Block stats (the iostat)",
 "Block latency (the p99)",
 "Block ioctl (the control)",
 "Block partition resize",
 "Block resize (the grow)",
 "Block online shrink",
 "Block read-only (the switch)",
 "Block verify (the scrub)",
 "Block self-test (the health)",
 "Block error injection (the test)",
 "Block quota (the per-volume)",
 "Block multi-queue (the SMP)",
 "Block interrupt coalescing",
 "Block poll mode (the busy)",
 "Block async I/O (the io_uring-ish)",
 "Block zero-copy (the splice)",
 "Block mmap (the direct)",
 "Block copy-on-read (the cache)",
 "Block cache tiering (the hot/cold)",
 "Block in-memory (the tmpfs)",
 "Block image formats (the qcow-ish)",
 "Block snapshot chains",
 "Block thin provisioning",
 "Block overcommit (the copy-on-write)",
 "Block sparse (the holes)",
 "Block punch (the hole)",
 "Block clone (the reflink)",
 "Block dedup inline (the live)",
 "Block compression inline",
 "Block encryption inline",
 "Block checksum inline",
 "Block write amplification (the counter)",
 "Block lifetime (the wear counter)",
 "Block health prediction",
 "Block retirement (the failing)",
 "Block remap on fail",
 "Block degraded mode (the RAID)",
 "Block rebuild (the resync)",
 "Block patrol read",
 "Block media scan",
 "Block self-healing (the parity)",
 "Block scrub scheduling",
 "Block notifications (the events)",
 "Block tests: the full matrix",
 "Block docs: the spec",
 "Block the roadmap: this bank",
], "AHCI -> NVMe -> CoW/RAID -> flash wear-leveling (littlefs) -> the 9P block namespace")

theme("FS-B", "The FAT family (the metal's own)", [
 "FAT12/16/32 read (the boot volume)",
 "FAT32 write (the boot volume)",
 "FAT directory cache",
 "FAT long file names (the VFAT)",
 "FAT cluster chains (the traversal)",
 "FAT free cluster tracking",
 "FAT fragmentation (the defrag)",
 "FAT write atomicity (the journal-ish)",
 "FAT power-loss recovery (the scan)",
 "FAT timestamp (the DOS time)",
 "FAT attributes (the hidden/system)",
 "FAT case sensitivity (the 8.3)",
 "FAT unicode (the UTF-16)",
 "FAT volume label",
 "FAT boot sector verify",
 "FAT BPB parsing (the geometry)",
 "FAT multiple FATs (the mirror)",
 "FAT dirty bit (the check)",
 "FAT chkdsk (the repair)",
 "FAT cluster size selection",
 "FAT large clusters (the 64K)",
 "FAT exFAT (the future)",
 "FAT on flash (the wear-aware)",
 "FAT on RAM disk (the fast)",
 "FAT on AHCI (the boot volume)",
 "FAT on the 9P (the bridge)",
 "FAT as the interchange (the USB)",
 "FAT directory iteration",
 "FAT file create/delete/rename",
 "FAT file truncate",
 "FAT file append",
 "FAT file seek (the cluster jump)",
 "FAT contiguous files (the fast)",
 "FAT defrag (the moving)",
 "FAT repair (the orphan clusters)",
 "FAT journal (the write-ahead)",
 "FAT check (the consistency)",
 "FAT test: the roundtrip suite",
 "FAT test: the power-cut simulator",
 "FAT fuzz: the corrupted BPB",
 "FAT benchmark: the MB/s",
 "FAT docs: the spec (the register)",
], "the metal boot volume -> VFAT/exFAT -> flash-aware FAT (littlefs lessons) -> the 9P bridge")

theme("FS-C", "The native TXFS (the ZealOS lineage)", [
 "TXFS design (the transactional)",
 "TXFS superblock",
 "TXFS tree structure (the B-tree-ish)",
 "TXFS transactions (the atomic)",
 "TXFS commit (the fsync)",
 "TXFS rollback (the crash)",
 "TXFS journal (the replay)",
 "TXFS snapshots (the branching)",
 "TXFS copy-on-write (the never-modify)",
 "TXFS free space (the bitmap)",
 "TXFS fragmentation (the aging)",
 "TXFS directories (the trees)",
 "TXFS files (the extents)",
 "TXFS extents (the contiguous)",
 "TXFS sparse files",
 "TXFS hard links",
 "TXFS symlinks",
 "TXFS permissions (the ACL)",
 "TXFS ownership (the users)",
 "TXFS xattrs (the metadata)",
 "TXFS timestamps (the nanosecond)",
 "TXFS versioning (the file history)",
 "TXFS dedup (the hashes)",
 "TXFS compression (the inline)",
 "TXFS encryption (the at-rest)",
 "TXFS checksums (the tree)",
 "TXFS scrub (the verify)",
 "TXFS repair (the self-heal)",
 "TXFS quotas (the per-user)",
 "TXFS resize (the grow)",
 "TXFS shrink (the careful)",
 "TXFS mount options (the tunables)",
 "TXFS the boot volume (the metal)",
 "TXFS the 9P bridge",
 "TXFS the AGI memory (the state store)",
 "TXFS the Bonzi memory (the moods)",
 "TXFS the ledger (the append-only)",
 "TXFS the snapshots (the system state)",
 "TXFS the rollback (the system restore)",
 "TXFS the GC (the deleted space)",
 "TXFS the defrag (the aging)",
 "TXFS the tests (the crash suite)",
 "TXFS the fuzz (the tree corruption)",
 "TXFS the benchmark (the ops/sec)",
 "TXFS the docs (the ZealOS parity)",
], "ZealOS TXFS -> transactional design -> CoW snapshots -> the AGI state store")

theme("FS-D", "The 9P namespace (everything is a file)", [
 "The 9P protocol (the version/auth/walk)",
 "The 9P fid lifecycle (the alloc/free)",
 "The 9P walk (the path resolution)",
 "The 9P open modes (the flags)",
 "The 9P read/write (the offset)",
 "The 9P clunk (the cleanup)",
 "The 9P stat/wstat (the metadata)",
 "The 9P remove (the delete)",
 "The 9P create (the mkdir/file)",
 "The 9P attach (the session)",
 "The 9P mount (the namespace)",
 "The 9P files (the everything)",
 "The /win namespace (the windows)",
 "The /apps namespace (the registry)",
 "The /dev namespace (the devices)",
 "The /sys namespace (the system)",
 "The /proc namespace (the processes)",
 "The /net namespace (the network)",
 "The /snd namespace (the synthesis)",
 "The /agix namespace (the AGI)",
 "The /bonzi namespace (the companion)",
 "The /mem namespace (the memory)",
 "The /time namespace (the clocks)",
 "The /rand namespace (the entropy)",
 "The /usr namespace (the users)",
 "The /etc namespace (the config)",
 "The /tmp namespace (the scratch)",
 "The /var namespace (the logs)",
 "The /boot namespace (the kernel)",
 "The /firmware namespace (the WuBuFW)",
 "The /host namespace (the host bridge)",
 "The /container namespace (the pods)",
 "The /9p-remote (the network mounts)",
 "The 9P client (the wubu bridge)",
 "The 9P server (the hosted)",
 "The 9P kernel server (the metal)",
 "The 9P auth (the tokens)",
 "The 9P permissions (the grants)",
 "The 9P quotas (the per-fid)",
 "The 9P cache (the page cache)",
 "The 9P sync (the flush)",
 "The 9P watch (the events)",
 "The 9P streams (the pipes-as-files)",
 "The 9P sockets (the network-as-files)",
 "The 9P devices (the hardware-as-files)",
 "The 9P windows (the GUI-as-files)",
 "The 9P apps (the launch-as-file)",
 "The 9P the Colonel (the eval-as-file)",
 "The 9P the AGI (the goal-as-file)",
 "The 9P the Bonzi (the mood-as-file)",
 "The 9P the EDR (the event-as-file)",
 "The 9P the verifier (the attest-as-file)",
 "The 9P the ledger (the append-as-file)",
 "The 9P tests (the protocol suite)",
 "The 9P fuzz (the malformed)",
 "The 9P bench (the ops/sec)",
 "The 9P docs (the Plan9 lineage)",
], "Plan9 -> Inferno -> the Styx/9P everything-as-file -> the AGI's whole world as files")

theme("FS-E", "The CoW & snapshots", [
 "Copy-on-write (the never-in-place)",
 "CoW extents (the reflink)",
 "CoW files (the clone)",
 "Snapshot (the point-in-time)",
 "Snapshot branching (the tree)",
 "Snapshot diff (the delta)",
 "Snapshot restore (the rollback)",
 "Snapshot export (the image)",
 "Snapshot import",
 "Snapshot GC (the orphan)",
 "Snapshot retention (the policy)",
 "Snapshot schedule (the cron)",
 "Snapshot verify (the checksum)",
 "Snapshot send/receive (the remote)",
 "Snapshot encryption",
 "Snapshot compression",
 "Snapshot dedup (the cross-snapshot)",
 "Snapshot the OS state (the system restore)",
 "Snapshot the user state (the backup)",
 "Snapshot the AGI state (the checkpoint)",
 "Snapshot the Bonzi state (the persona)",
 "Snapshot the kernel (the boot rollback)",
 "Snapshot the firmware (the WuBuFW rollback)",
 "Snapshot the boot volume",
 "Snapshot the home",
 "Snapshot the config",
 "Snapshot the logs",
 "Snapshot the database",
 "Snapshot the container (the layer)",
 "Snapshot the VM (the future)",
 "Snapshot the tests (the restore suite)",
 "Snapshot the fuzz (the corruption)",
 "Snapshot the bench (the restore ms)",
 "Snapshot the docs (the spec)",
], "ZFS/btrfs CoW -> snapshot trees -> the system restore -> the AGI checkpointing")

theme("FS-F", "The databases & stores (the AGI's memory)", [
 "The KV store (the key-value)",
 "The KV persistence (the WAL)",
 "The KV cache (the LRU)",
 "The KV tiers (the hot/cold)",
 "The B-tree store (the ordered)",
 "The LSM tree (the write-optimized)",
 "The column store (the analytics)",
 "The document store (the JSON)",
 "The graph store (the links)",
 "The vector store (the embeddings)",
 "The vector index (the HNSW-ish)",
 "The full-text index (the inverted)",
 "The WAL (the write-ahead)",
 "The checkpoint (the flush)",
 "The compaction (the LSM)",
 "The merge (the SST)",
 "The bloom filters (the prob)",
 "The transactions (the atomic)",
 "The isolation (the levels)",
 "The concurrency (the MVCC)",
 "The locking (the optimistic)",
 "The recovery (the replay)",
 "The corruption detection (the checksums)",
 "The repair (the self-heal)",
 "The backup (the dump)",
 "The restore (the load)",
 "The migration (the versioned)",
 "The replication (the future)",
 "The sharding (the future)",
 "The queries (the declarative)",
 "The indexes (the secondary)",
 "The schema (the versioned)",
 "The migration (the alter)",
 "The joins (the hash)",
 "The aggregates (the group)",
 "The window functions (the analytics)",
 "The time-series (the append)",
 "The retention (the TTL)",
 "The compression (the column)",
 "The encryption (the at-rest)",
 "The audit (the append-only)",
 "The KV for the AGI memory (the facts)",
 "The KV for the Bonzi (the moods)",
 "The KV for the settings (the config)",
 "The KV for the ledger (the events)",
 "The KV for the caches (the hot)",
 "The KV for the sessions (the state)",
 "The KV for the tasks (the todo)",
 "The KV for the goals (the bank)",
 "The KV for the sources (the archive)",
 "The store tests (the roundtrip)",
 "The store fuzz (the corruption)",
 "The store bench (the ops/sec)",
 "The store docs (the spec)",
], "WAL/LSM (RocksDB lineage) -> the vector store -> the AGI's fact + memory + source stores")

theme("FS-G", "The compression & dedup", [
 "The zlib deflate (the classic)",
 "The zstd (the modern)",
 "The LZ4 (the fast)",
 "The LZMA (the ratio)",
 "The brotli (the text)",
 "The Huffman (the entropy)",
 "The arithmetic coding (the future)",
 "The delta encoding (the versioned)",
 "The dictionary (the repeated)",
 "The block compression (the FS)",
 "The file compression (the per-file)",
 "The stream compression (the pipe)",
 "The network compression (the 9P)",
 "The log compression (the rotate)",
 "The image compression (the PNG)",
 "The audio compression (the WAV->FLAC)",
 "The video compression (the future)",
 "The dedup (the content hash)",
 "The dedup inline (the write path)",
 "The dedup offline (the scan)",
 "The dedup cross-file",
 "The dedup cross-snapshot",
 "The dedup the AGI sources (the archive)",
 "The dedup the wavetable (the frames)",
 "The dedup the KV (the repeated)",
 "The dedup tests (the hashes)",
 "The dedup bench (the ratio)",
 "The compression bench (the MB/s)",
 "The compression docs (the spec)",
], "zlib -> zstd -> content-hash dedup -> the AGI source archive")

theme("FS-H", "The memory & tmpfs", [
 "The tmpfs (the RAM disk)",
 "The page cache (the files)",
 "The dentry cache (the paths)",
 "The inode cache (the metadata)",
 "The buffer cache (the blocks)",
 "The read-ahead (the sequential)",
 "The write-behind (the dirty)",
 "The writeback (the flush)",
 "The reclaim (the LRU)",
 "The pressure (the memory)",
 "The OOM (the killer)",
 "The swap (the 8-sector swap)",
 "The swap the AGI (the KV offload)",
 "The mmap (the shared)",
 "The madvise (the hints)",
 "The mlock (the pinned)",
 "The huge pages (the THP)",
 "The NUMA (the local)",
 "The cgroup (the limit)",
 "The quota (the per-user)",
 "The tmpfs the boot (the initrd)",
 "The tmpfs the logs (the volatile)",
 "The tmpfs the AGI scratch",
 "The tmpfs the compile (the JIT)",
 "The memory tests (the allocator)",
 "The memory bench (the MB/s)",
 "The memory docs (the spec)",
], "page cache -> tmpfs -> the swap -> the AGI's memory tiers")

theme("FS-I", "The flash & wear (the metal storage)", [
 "The flash model (the erase-before-write)",
 "The wear leveling (the equal)",
 "The write amplification (the counter)",
 "The read disturb (the refresh)",
 "The data retention (the refresh)",
 "The bad blocks (the map)",
 "The spare blocks (the pool)",
 "The GC of flash (the reclaim)",
 "The over-provisioning (the headroom)",
 "The TRIM (the discard)",
 "The secure erase (the wipe)",
 "The flash controller (the FTL-ish)",
 "The littlefs lessons (the design)",
 "The power-loss safety (the brownout)",
 "The checksums (the detect)",
 "The copy-back (the verify)",
 "The multi-plane (the parallel)",
 "The interleaving (the channels)",
 "The ECC (the correction)",
 "The metadata protection",
 "The flash the boot volume (the metal)",
 "The flash the SD card (the future)",
 "The flash the eMMC (the future)",
 "The flash the USB (the future)",
 "The flash tests (the wear sim)",
 "The flash bench (the writes)",
 "The flash docs (the spec)",
], "NOR/NAND physics -> littlefs -> wear leveling -> the metal boot storage")

theme("FS-J", "The storage avenue engineering", [
 "The storage module registry",
 "The block test suite",
 "The FS test suite",
 "The 9P test suite",
 "The crash-simulator (the power cuts)",
 "The corruption injector",
 "The repair validator",
 "The benchmark harness",
 "The energy accounting (the J)",
 "The telemetry (the io stats)",
 "The watchdog (the hang)",
 "The quarantine (the bad media)",
 "The docs (the spec)",
 "The roadmap (this bank)",
], "the engineering discipline for the whole storage avenue")

with open("docs/compendium/04-roadmap/storage-bank.md", "w") as f:
    f.write("# Storage Bank -- 1000 goals + gaps (the metal's data)\n\n")
    f.write("Date: 2026-08-02. The storage avenue: the block layer, FAT, TXFS,\n")
    f.write("9P namespace, CoW/snapshots, databases, compression, tmpfs, flash.\n")
    f.write("Status: `open` / `wired`. Every gap is a real mechanism from the\n")
    f.write("surveyed lineage (AHCI->NVMe->CoW->littlefs->LSM stores).\n")
    f.write("".join(T))
print("storage bank:", len([l for l in T if l.startswith("- FS-")]))
