#!/usr/bin/env python3
"""GUI gap index: 1000 goals+gaps across 10 themes (GU-A..GU-J).
The 'best most modular AI-powered OS ever' GUI register. Every gap is
a real GUI/OS mechanism written as a C11-shaped goal. Everything flows
through the HolyC Colonel (the TempleOS lineage): apps, OS code, and
cross-OS payloads all dispatch through the Colonel."""
T = []
def theme(name, title, gaps, refs):
    T.append(f"\n## {name}: {title}\nStatus: `open` = not yet built; `wired` = implemented + tested.\n### 7-hop convergence: {refs}\n")
    for i, g in enumerate(gaps, 1):
        T.append(f"- {name}{i:02d} {g} `open`\n")
    T.append(f"Status: `open` ({len(gaps)} gaps)\n")

theme("GU-A", "The windowing core", [
 "Focus model (click-to-focus + focus-follows-mouse modes)",
 "Z-order management (raise/lower/always-on-top)",
 "Drag-move with the live preview",
 "Resize with the edge/corner handles",
 "Minimize/maximize/restore state machine",
 "Aero-snap (left/right/quadrant snap)",
 "Keyboard-driven window placement (win+arrows)",
 "Virtual desktops (spaces with per-desktop windows)",
 "Window groups (tabbed windows)",
 "Window stacking (cascade/tile)",
 "Multi-monitor awareness (per-monitor DPI)",
 "DPI scaling (per-monitor 100-200%)",
 "Window persistence (restore layout at boot)",
 "Window state snapshot (crash recovery)",
 "Per-window opacity",
 "Window shake-to-minimize",
 "Window roll-up (titlebar collapse)",
 "Window shake-to-peek",
 "Alt-Tab switcher (with live thumbnails)",
 "Taskbar preview thumbnails",
 "Window borders (themed chrome)",
 "Client-area vs chrome-area hit testing",
 "Window message routing (the Colonel dispatch)",
 "Window event queue (bounded, priority)",
 "Window timer events (per-window tick)",
 "Window invalidation (damage tracking)",
 "Window occlusion culling (hidden = no render)",
 "Window focus ring (accessibility)",
 "Modal windows (dialog modality)",
 "Window owner relationships (child windows)",
 "Popup windows (transient)",
 "Tooltip windows (delayed show)",
 "Menu windows (dismiss on outside-click)",
 "Window-level undo (restore closed window)",
 "Window registry (all windows discoverable)",
 "Window telemetry (per-window CPU/fps)",
 "Window GPU-acceleration (the compositor path)",
 "Window software fallback (llvmpipe-safe)",
 "Window resize smoothness (no tearing)",
 "Window scroll wheel routing",
 "Window drag-drop target (the OLE-ish)",
 "Window clipboard integration",
 "Window keyboard shortcuts (per-window)",
 "Window speech (the screen-reader hooks)",
 "Window motion (the transitions engine)",
 "Window sounds (the OS event sounds)",
 "Window theming (per-window theme override)",
 "Window localization (RTL support)",
 "Window IME input (per-window)",
 "Window touch handling (per-window)",
 "Window gestures (per-window)",
 "Window memory budget (per-window cap)",
 "Window leak detection (the GC watch)",
 "Window frame rate governor (idle = low fps)",
 "Window energy accounting (the IJ ledger tie)",
 "Window debug overlay (the inspector)",
 "Window test suite (the WM asserts)",
 "Window fuzz (adversarial events)",
 "Window benchmark (100-window stress)",
 "Window state serialization (the 9P export)",
 "Window remote control (the 9P window protocol)",
 "Window nesting (embed a window in a window)",
 "Window compositing (the double-buffer)",
 "Window partial damage (dirty rects)",
 "Window triple-buffering (the future)",
 "Window present timing (vsync)",
 "Window adaptive refresh (the power save)",
 "Window cursor handling (per-window cursors)",
 "Window icon (the taskbar + alt-tab)",
 "Window class registration (the app framework)",
 "Window style bits (the Win32-style)",
 "Window extended styles (the modern)",
 "Window messages (the wm_* enum)",
 "Window procedure (the dispatch table)",
 "Window creation path (the Colonel gated)",
 "Window destruction path (the cleanup)",
 "Window enumeration (the 9P /win namespace)",
 "Window focus history (the alt-tab MRU)",
 "Window activation policy (the rules)",
 "Window transparency hit-testing",
 "Window snap layouts (the 11-style)",
 "Window corner rounding (the XP vibes)",
 "Window shadow (the soft shadow)",
 "Window glow (the active glow)",
 "Window animations (open/close/minimize)",
 "Window open animation (the grow)",
 "Window close animation (the shrink)",
 "Window minimize animation (to taskbar)",
 "Window restore animation (from taskbar)",
 "Window shake (the find-window shake)",
 "Window magnifier (the loupe)",
 "Window region clipping (the complex shapes)",
 "Window layered windows (the WS_EX_LAYERED)",
 "Window key preview (the before-dispatch)",
 "Window mouse capture (the drag capture)",
 "Window focus steal prevention",
 "Window message coalescing (the burst filter)",
 "Window render cache (the static-window fast path)",
 "Window idle render (the static = no redraw)",
 "Window test: the 10K-message soak",
], "Win98 WM -> XP/Win11 windowing -> Wayland compositing -> the Colonel dispatch")

theme("GU-B", "The chrome & rendering", [
 "Title bar (themed gradient + text + buttons)",
 "Title bar buttons (min/max/close with states)",
 "Title bar drag region",
 "Control bevels (the Win98 3D look)",
 "Button states (normal/hover/pressed/disabled)",
 "Checkbox + radio rendering",
 "Scrollbar rendering (themed)",
 "Slider rendering (the volume bar family)",
 "Combo box rendering",
 "Menu rendering (the hover + submenu)",
 "Toolbar rendering (the icon buttons)",
 "Status bar rendering (the panels)",
 "Tab strip rendering (the terminal tabs)",
 "Progress bar rendering (the XP glow)",
 "Tooltip rendering (the delayed bubble)",
 "Text rendering (the 64-glyph font family)",
 "Font scaling (the DPI)",
 "Font anti-aliasing (the gray-scale)",
 "Icon rendering (the pixel-glyph family)",
 "Icon states (the selected plate)",
 "Cursor rendering (the animated cursors)",
 "Window shadow (the soft drop shadow)",
 "Window glow (the active-state glow)",
 "Focus rectangle (the dotted XP style)",
 "Selection plate (the navy translucent)",
 "Drag ghost (the translucent drag preview)",
 "Rounded corners (the radius from the theme)",
 "Gradients (the title bar + the start menu)",
 "Borders (the bevels + the resize edges)",
 "The compositor (the double-buffer)",
 "The compositor damage tracking",
 "The compositor partial presents",
 "The compositor GPU path (the Vulkan)",
 "The compositor fallback (the VBE)",
 "The pixel formats (RGB565/RGB888/ARGB)",
 "The scaling filter (the smooth upscale)",
 "The color management (the gamma)",
 "The high-contrast mode (the theme)",
 "The dark mode (the theme)",
 "The theme engine (the 5+ themes)",
 "The theme live-switch (no restart)",
 "The theme persistence (the settings)",
 "The theme accent colors (the per-app)",
 "The theme sound schemes (the Win98/XP)",
 "The wallpaper engine (the stretch/tile/center)",
 "The wallpaper slideshow (the rotation)",
 "The wallpaper live (the animated)",
 "The screensaver (the blank + the moving)",
 "The boot splash (the themed)",
 "The login screen (the themed)",
 "The shutdown screen (the themed)",
 "The pixel-art glyph set (the 32x32 family)",
 "The glyph theme mapping (the 4-color)",
 "The text measuring (the width calc)",
 "The text wrapping (the word wrap)",
 "The text ellipsis (the truncation)",
 "The text selection (the inverse)",
 "The text cursor (the blinking)",
 "The text scrolling (the smooth)",
 "The line spacing (the leading)",
 "The glyph cache (the fast path)",
 "The render test (the pixel asserts)",
 "The render benchmark (the fps)",
 "The render fuzz (the garbage params)",
 "The render thread (the async present)",
 "The render priority (the foreground first)",
 "The render budget (the frame time)",
 "The render energy (the IJ ledger)",
 "The blur (the frosted glass)",
 "The transparency (the per-window alpha)",
 "The rounded window masks",
 "The animated transitions (the crossfade)",
 "The morph transitions (the grow/shrink)",
 "The easing curves (the cubic/overshoot)",
 "The motion-reduction mode (the accessibility)",
 "The color-blind palettes (the theme)",
 "The OLED dark (the pure black)",
 "The paper white (the reading mode)",
 "The sepia (the reading comfort)",
 "The contrast adjust (the slider)",
 "The saturation adjust (the slider)",
 "The hue shift (the filter)",
 "The night light (the blue reduction)",
 "The render queue (the frame ordering)",
 "The render isolation (the app can't corrupt)",
 "The render telemetry (the per-frame stats)",
 "The render watchdog (the hang detection)",
 "The Chrome-standard (the window-standardization)",
 "The chrome test (the 9 themes x controls)",
 "The chrome benchmark (the paint cost)",
 "The chrome fuzz (the malformed themes)",
 "The chrome docs (the theme spec)",
 "The Colonel chrome (the HolyC-drawn chrome)",
 "The GPU chrome (the Vulkan-composited)",
 "The chrome energy (the idle = zero paint)",
 "The chrome accessibility (the contrast audit)",
], "Win98 bevels -> XP Luna glass -> Wayland compositing -> HolyC-drawn chrome")

theme("GU-C", "The desktop & shell", [
 "Desktop icons (the pixel-glyph family)",
 "Icon selection (the navy plate)",
 "Icon drag (the snap-to-grid)",
 "Icon auto-arrange (the persist)",
 "Icon rename (the inline edit)",
 "Icon delete (the Recycle Bin)",
 "Icon properties (the dialog)",
 "Desktop context menu (the New/View/Refresh)",
 "Desktop wallpaper (the center/tile/stretch)",
 "Desktop widgets (the clock/weather/CPU)",
 "Desktop gadgets (the mini-apps)",
 "Desktop scrolling (the pages)",
 "Taskbar (the themed bar)",
 "Taskbar buttons (the running windows)",
 "Taskbar grouping (the same-app stacks)",
 "Taskbar hover (the preview)",
 "Taskbar clock (the HH:MM)",
 "Taskbar tray (the icons)",
 "Taskbar notification badges",
 "Taskbar quick-launch (the pins)",
 "Taskbar auto-hide",
 "Taskbar position (the 4 edges)",
 "Taskbar multi-monitor",
 "Start menu (the two-column XP layout)",
 "Start menu search (the live filter)",
 "Start menu recent programs (the MRU)",
 "Start menu All Programs (the tree)",
 "Start menu power (the shutdown/restart)",
 "Start menu pins (the user favorites)",
 "Start menu the Colonel (the HolyC command)",
 "Notification center (the sliding panel)",
 "Notification actions (the reply/clear)",
 "Notification urgency (the colors)",
 "Notification history (the log)",
 "Notification sounds (the events)",
 "Quick settings (the toggles)",
 "Volume mixer (the per-app)",
 "Wi-Fi quick toggle",
 "Brightness quick toggle",
 "Bluetooth quick toggle",
 "Battery indicator",
 "Network indicator",
 "Keyboard layout indicator",
 "Desktop search (the global find)",
 "Desktop file search (the index)",
 "Desktop app search (the launcher)",
 "Desktop settings (the Control Panel)",
 "Desktop themes (the applier)",
 "Desktop sounds (the scheme applier)",
 "Desktop wallpaper picker (the gallery)",
 "Desktop slideshow (the rotation)",
 "Desktop virtual desktops (the switcher)",
 "Desktop overview (the expose)",
 "Desktop preview (the peek)",
 "Desktop snap (the layouts)",
 "Desktop widgets bar (the panel)",
 "Desktop clock widget (the analog)",
 "Desktop weather widget",
 "Desktop CPU widget (the meter)",
 "Desktop memory widget",
 "Desktop network widget (the graph)",
 "Desktop disk widget",
 "Desktop battery widget",
 "Desktop calendar widget",
 "Desktop notes widget (the sticky)",
 "Desktop todo widget",
 "Desktop RSS widget",
 "Desktop music widget (the now playing)",
 "Desktop AGI widget (the status)",
 "Desktop Bonzi widget (the companion)",
 "Desktop folder (the desktop IS a folder)",
 "Desktop path (the 9P ~/Desktop)",
 "Desktop persistence (the layout save)",
 "Desktop restore (the boot restore)",
 "Desktop cleanup (the clutter manager)",
 "Desktop grouping (the folders)",
 "Desktop sorting (the by name/type/date)",
 "Desktop renaming (the F2)",
 "Desktop delete (the trash)",
 "Desktop drag-drop (the apps/urls)",
 "Desktop shortcuts (the .lnk-ish)",
 "Desktop URL shortcuts (the web)",
 "Desktop mount points (the drives)",
 "Desktop network places (the 9P)",
 "Desktop recycle bin (the restore)",
 "Desktop empty-state (the first boot)",
 "Desktop onboarding (the tour)",
 "Desktop security (the lock screen)",
 "Desktop lock (the screen lock)",
 "Desktop user switch (the sessions)",
 "Desktop guest mode (the ephemeral)",
 "Desktop multi-user (the profiles)",
 "Desktop permissions (the app sandbox)",
 "Desktop telemetry (the user consent)",
 "Desktop privacy (the no-telemetry default)",
 "Desktop energy (the idle dimming)",
 "Desktop sleep (the suspend)",
 "Desktop hibernate (the resume)",
 "Desktop fast startup (the cached shell)",
 "Desktop crash recovery (the shell watchdog)",
 "Desktop test (the full shell suite)",
 "Desktop benchmark (the boot-to-desktop time)",
 "Desktop fuzz (the shell events)",
 "Desktop docs (the user guide)",
], "Win98 shell -> XP Start/taskbar -> Win11 widgets -> the 9P desktop-as-folder")

theme("GU-D", "The apps (the built-in family)", [
 "Calculator (the standard)",
 "Calculator (the scientific)",
 "Calculator (the programmer)",
 "Notepad (the plain text)",
 "Notepad (the search)",
 "Notepad (the autosave)",
 "Paint (the canvas)",
 "Paint (the brushes)",
 "Paint (the shapes)",
 "File Manager (the two-pane)",
 "File Manager (the tree)",
 "File Manager (the preview)",
 "Terminal (the PTY)",
 "Terminal (the tabs)",
 "Terminal (the HolyC session)",
 "Terminal (the scrollback search)",
 "Terminal (the ANSI)",
 "Control Panel (the applets)",
 "Control Panel (the display applet)",
 "Control Panel (the network applet)",
 "Control Panel (the sound applet)",
 "Control Panel (the theme applet)",
 "Task Manager (the processes)",
 "Task Manager (the kill)",
 "Task Manager (the CPU graph)",
 "Music player (the WAV/MP3/OGG)",
 "Music player (the playlist)",
 "Music player (the synthesis jams)",
 "Image viewer (the PNG/JPG)",
 "Image viewer (the zoom)",
 "Video player (the MP4)",
 "Browser (the web)",
 "Browser (the tabs)",
 "Browser (the bookmarks)",
 "Email client (the SMTP/IMAP)",
 "Chat client (the 9P messaging)",
 "Text editor (the code)",
 "Text editor (the syntax)",
 "Text editor (the LSP)",
 "IDE (the build)",
 "IDE (the debug)",
 "The Colonel IDE (the HolyC editor)",
 "The Colonel REPL (the HolyC terminal)",
 "The HolyC debugger (the breakpoints)",
 "The package manager GUI (the pacman)",
 "The container manager GUI (the pods)",
 "The snapshot GUI (the restore)",
 "The network GUI (the firewall)",
 "The disk GUI (the format)",
 "The disk GUI (the partitions)",
 "The settings app (the aggregated)",
 "The accessibility app",
 "The sound lab (the synthesis)",
 "The wavetable editor (the frames)",
 "The spectrum analyzer (the live)",
 "The oscilloscope (the live)",
 "The MIDI app (the keyboard)",
 "The drum machine (the pads)",
 "The step sequencer (the patterns)",
 "The Bonzi app (the companion)",
 "The Comfy app (the AGI dispatch)",
 "The AGI status app (the loop)",
 "The AGI inspector (the memory)",
 "The AGI planner (the goals)",
 "The AGI ledger (the DA audit)",
 "The EDR dashboard (the security)",
 "The log viewer (the kernel log)",
 "The system monitor (the sensors)",
 "The hardware info app (the hwdetect)",
 "The boot log viewer (the A9 codes)",
 "The verifier app (the attestation)",
 "The user guide (the help)",
 "The tutorial app (the onboarding)",
 "The games (the FreeDoom)",
 "The games (the chess)",
 "The games (the minesweeper)",
 "The games (the solitaire)",
 "The games (the snake)",
 "The screensaver preview",
 "The clock app (the world time)",
 "The calendar app (the events)",
 "The weather app",
 "The calculator unit (the conversions)",
 "The notes app (the sticky)",
 "The todo app (the tasks)",
 "The OCR app (the text from image)",
 "The clipboard history (the manager)",
 "The screenshot app (the region)",
 "The screen recorder",
 "The magnifier app",
 "The character map",
 "The run dialog (the win+R)",
 "The file association app (the MIME)",
 "The default apps app",
 "The uninstaller app",
 "The software center (the curated)",
 "The update app (the system)",
 "The backup app (the snapshot)",
 "The restore app (the rollback)",
 "The app framework (the registry)",
 "The app test suite (the smoke)",
 "The app benchmark (the launch time)",
 "The app docs (the developer guide)",
], "Win98 accessories -> the XP suite -> the AGI apps (Bonzi/Comfy/inspector) -> the Colonel IDE")

theme("GU-E", "The input & accessibility", [
 "Keyboard input (the scancode map)",
 "Keyboard repeat (the OS-level)",
 "Keyboard layout switching (the IME)",
 "Keyboard shortcuts (the global registry)",
 "Mouse input (the motion)",
 "Mouse buttons (the 5-button)",
 "Mouse wheel (the smooth scroll)",
 "Mouse acceleration (the curve)",
 "Mouse capture (the drag)",
 "Mouse cursor hotspot (the pixel)",
 "Touch input (the multi-touch)",
 "Touch gestures (the pinch/swipe)",
 "Stylus input (the pressure)",
 "Pen tilt (the stylus)",
 "Gamepad input (the joystick)",
 "Motion input (the accelerometer)",
 "Text input (the composition)",
 "IME (the CJK)",
 "IME (the on-screen keyboard)",
 "Autocomplete (the suggestions)",
 "Auto-correct (the typos)",
 "Spellcheck (the red underline)",
 "Clipboard (the text)",
 "Clipboard (the images)",
 "Clipboard (the history)",
 "Drag-drop (the OLE-ish)",
 "Drag-drop (the files)",
 "Drag-drop (the text)",
 "Focus navigation (the tab order)",
 "Focus ring (the visible)",
 "Arrow-key navigation (the controls)",
 "Screen reader (the text-to-speech)",
 "Screen reader (the UI tree)",
 "High contrast (the theme)",
 "Font scaling (the 100-200%)",
 "Text scaling (the magnifier)",
 "Color-blind palettes (the theme)",
 "Motion reduction (the accessibility)",
 "Sticky keys (the one-hand)",
 "Slow keys (the tremor)",
 "Bounce keys (the double-press)",
 "Toggle keys (the alert)",
 "Mouse keys (the numpad)",
 "Narrator (the full reader)",
 "Live captions (the speech-to-text)",
 "Voice input (the dictation)",
 "Eye tracking (the future)",
 "Switch access (the scanning)",
 "Braille display (the future)",
 "The accessibility test suite",
 "The accessibility audit (the WCAG-ish)",
 "The accessibility report (the contrast)",
 "The accessibility settings app",
 "The accessibility quick-toggle (the shortcut)",
 "The input latency budget (the <16ms)",
 "The input priority (the realtime)",
 "The input coalescing (the burst)",
 "The input queue (the bounded)",
 "The input fuzz (the garbage events)",
 "The input benchmark (the 10K events)",
 "The input test (the synthetic)",
 "The input recorder (the macro)",
 "The input playback (the demo)",
 "The input replay (the debug)",
 "The input capture (the games)",
 "The input exclusivity (the modal)",
 "The input routing (the Colonel dispatch)",
 "The input mapping (the remap)",
 "The input profiles (the per-app)",
 "The input energy (the idle polling)",
 "The input wake (the wake-on-key)",
 "The keyboard LED (the caps lock)",
 "The keyboard firmware (the 9P)",
 "The mouse firmware (the 9P)",
 "The touch firmware (the 9P)",
 "The hotkey daemon (the global)",
 "The shortcut editor (the UI)",
 "The shortcut conflicts (the resolver)",
 "The shortcut discovery (the docs)",
 "The command palette (the ctrl+shift+p)",
 "The palette fuzzy match",
 "The palette actions (the every-command)",
 "The palette history",
 "The gesture editor (the custom)",
 "The mouse gestures (the strokes)",
 "The touch gestures (the custom)",
 "The input module docs",
], "Keyboard/mouse basics -> multi-touch -> IME -> screen-reader -> the Colonel-routed input")

theme("GU-F", "The IPC & namespace", [
 "The 9P namespace (the everything-is-a-file)",
 "The /win namespace (the windows as files)",
 "The /apps namespace (the apps as files)",
 "The /dev namespace (the devices)",
 "The /sys namespace (the system)",
 "The /proc namespace (the processes)",
 "The /net namespace (the network)",
 "The /snd namespace (the synthesis)",
 "The /agix namespace (the AGI)",
 "The /bonzi namespace (the companion)",
 "The window protocol (the 9P window ops)",
 "The clipboard protocol (the 9P read/write)",
 "The drag-drop protocol (the 9P move)",
 "The DDE-ish (the dynamic data)",
 "The OLE-ish (the object embedding)",
 "The app messaging (the pub/sub)",
 "The service registry (the discover)",
 "The event bus (the system events)",
 "The app-to-app calls (the RPC)",
 "The remote desktop (the 9P view)",
 "The session sharing (the multi-user)",
 "The window forwarding (the remote)",
 "The app sandbox (the seccomp)",
 "The app isolation (the cgroups)",
 "The app permissions (the grants)",
 "The app data (the per-app dirs)",
 "The app config (the settings)",
 "The app state (the snapshot)",
 "The app upgrade (the versioned)",
 "The app rollback (the previous)",
 "The app signing (the attestation)",
 "The app provenance (the ledger)",
 "The app energy (the per-app budget)",
 "The app watchdog (the hang kill)",
 "The app crash report (the dialog)",
 "The app crash recovery (the restart)",
 "The app unresponsive (the dim)",
 "The app telemetry (the consent)",
 "The app privacy (the no-default)",
 "The namespace test suite",
 "The namespace fuzz (the malformed 9P)",
 "The namespace benchmark (the ops/sec)",
 "The namespace docs (the spec)",
 "The clipboard sync (the OS-level)",
 "The clipboard security (the redact)",
 "The drag-drop security (the verify)",
 "The IPC security (the authenticate)",
 "The IPC encryption (the localhost TLS)",
 "The IPC priority (the realtime)",
 "The IPC backpressure (the bounded)",
 "The IPC coalescing (the burst)",
 "The IPC the Colonel (the HolyC message)",
 "The IPC the AGI (the goal messages)",
 "The IPC the Bonzi (the mood messages)",
 "The IPC the EDR (the events)",
 "The IPC the verifier (the attest)",
 "The IPC the console (the commands)",
 "The IPC the firmware (the WuBuFW)",
 "The IPC the kernel (the syscalls)",
 "The IPC the VSL (the NT translation)",
 "The IPC the containers (the 9P mount)",
 "The IPC the network (the remote 9P)",
 "The IPC the web (the fetch)",
 "The IPC the localhost (the loopback)",
 "The IPC the unix sockets",
 "The IPC the shared memory",
 "The IPC the pipes",
 "The IPC the signals",
 "The IPC the timers",
 "The IPC the clocks",
 "The IPC the entropy",
 "The IPC the random",
 "The IPC the UUIDs",
 "The IPC the serialization (the JSON)",
 "The IPC the serialization (the binary)",
 "The IPC the schemas (the versioned)",
 "The IPC the errors (the typed)",
 "The IPC the logging (the structured)",
 "The IPC the tracing (the spans)",
 "The IPC the metrics (the counters)",
 "The IPC the health (the pings)",
 "The IPC the discovery (the mDNS-ish)",
 "The IPC the handoff (the session)",
 "The IPC the resume (the state)",
 "The IPC the undo (the journal)",
 "The IPC the redo",
 "The IPC the transactions",
 "The IPC the locks (the lease)",
 "The IPC the queues (the FIFO)",
 "The IPC the ring (the bounded)",
 "The IPC the fanout (the broadcast)",
 "The IPC the filter (the subscribe)",
 "The IPC the transform (the pipeline)",
 "The IPC the test (the 100-app)",
 "The IPC the benchmark (the msgs/sec)",
 "The IPC the fuzz (the 9P mutation)",
 "The IPC the docs (the protocol)",
], "Plan9/Inferno namespace -> 9P windows -> the AGI/Bonzi/EDR buses -> the Colonel-routed IPC")

theme("GU-G", "The AGI-GUI (the brain's face)", [
 "The Bonzi companion (the avatar)",
 "The Bonzi moods (the valence/arousal)",
 "The Bonzi animations (the idle/bounce)",
 "The Bonzi speech (the TTS)",
 "The Bonzi listening (the STT)",
 "The Bonzi memory (the Hopfield recall)",
 "The Bonzi learning (the user model)",
 "The Bonzi suggestions (the proactive)",
 "The Bonzi notifications (the moods)",
 "The Bonzi settings (the persona)",
 "The Comfy dispatch (the real command)",
 "The Comfy pipeline (the image gen)",
 "The Comfy the OS (the desktop control)",
 "The AGI status widget (the live loop)",
 "The AGI activity (the sonification)",
 "The AGI thoughts (the ticker)",
 "The AGI goals (the planner view)",
 "The AGI ledger (the DA audit view)",
 "The AGI memory (the inspector)",
 "The AGI recalls (the search)",
 "The AGI suggestions (the chips)",
 "The AGI asks (the clarify dialog)",
 "The AGI voice (the TTS)",
 "The AGI listening (the STT)",
 "The AGI vision (the screen read)",
 "The AGI actions (the confirmed)",
 "The AGI undo (the action journal)",
 "The AGI permissions (the grants)",
 "The AGI energy (the budget view)",
 "The AGI alignment (the values view)",
 "The AGI provenance (the every-action ledger)",
 "The AGI the OS (the control)",
 "The AGI the kernel (the ring-0)",
 "The AGI the Colonel (the HolyC eval)",
 "The AGI the compiler (the codegen)",
 "The AGI the tests (the self-test)",
 "The AGI the gaps (the bank view)",
 "The AGI the closing (the progress)",
 "The AGI the fanfare (the achievements)",
 "The AGI the tutor (the explain)",
 "The AGI the mentor (the guide)",
 "The AGI the critic (the DA view)",
 "The AGI the explorer (the curiosity)",
 "The AGI the artist (the canvas)",
 "The AGI the composer (the music)",
 "The AGI the sound designer (the patches)",
 "The AGI the UI designer (the adaptive)",
 "The AGI the adaptive UI (the layout)",
 "The AGI the adaptive themes (the mood)",
 "The AGI the proactive (the anticipate)",
 "The AGI the reactive (the respond)",
 "The AGI the collaborative (the co-edit)",
 "The AGI the delegated (the tasks)",
 "The AGI the monitored (the oversight)",
 "The AGI the audited (the triple-DA)",
 "The AGI the honest (the calibration)",
 "The AGI the private (the local)",
 "The AGI the secure (the attestation)",
 "The AGI the accessible (the voice-first)",
 "The AGI the multimodal (the text/voice/vision)",
 "The AGI the multilingual (the 100+ langs)",
 "The AGI the personalized (the user model)",
 "The AGI the contextual (the app-aware)",
 "The AGI the stateful (the session)",
 "The AGI the memory (the persistent)",
 "The AGI the forgetful (the unlearning)",
 "The AGI the curious (the novelty)",
 "The AGI the playful (the jokes)",
 "The AGI the kind (the empathy)",
 "The AGI the honest (the limits)",
 "The AGI the safe (the guardrails)",
 "The AGI the aligned (the values)",
 "The AGI the explainable (the reasons)",
 "The AGI the inspectable (the traces)",
 "The AGI the controllable (the off switch)",
 "The AGI the testable (the suite)",
 "The AGI the benchmark (the eval)",
 "The AGI the upgradeable (the weights)",
 "The AGI the versioned (the model registry)",
 "The AGI the A/B (the compare)",
 "The AGI the rollback (the previous)",
 "The AGI the observability (the metrics)",
 "The AGI the telemetry (the local)",
 "The AGI the audit log (the append-only)",
 "The AGI the forensics (the replay)",
 "The AGI the compliance (the GDPR-ish)",
 "The AGI the deletion (the right-to-forget)",
 "The AGI the export (the data portability)",
 "The AGI the import (the resume)",
 "The AGI the onboarding (the first run)",
 "The AGI the tutorial (the tour)",
 "The AGI the help (the F1)",
 "The AGI the docs (the self-documenting)",
 "The AGI the test (the GUI suite)",
 "The AGI the benchmark (the interaction)",
 "The AGI the fuzz (the prompts)",
 "The AGI the roadmap (this bank)",
], "The Bonzi + the Comfy + the loop's face -> the AGI as the OS's own UI -> everything Colonel-gated")

theme("GU-H", "The modularity & the Colonel", [
 "The app module registry (the discover)",
 "The app ABI (the stable)",
 "The app API (the documented)",
 "The app framework (the wubufx)",
 "The app lifecycle (the init/run/exit)",
 "The app hot-reload (the dev loop)",
 "The app sandbox (the seccomp)",
 "The app isolation (the cgroups)",
 "The app permissions (the grant)",
 "The app signing (the attest)",
 "The app versioning (the semver)",
 "The app dependencies (the graph)",
 "The app plugins (the extension)",
 "The app themes (the per-app)",
 "The app fonts (the embed)",
 "The app assets (the 9P mount)",
 "The app config (the JSON)",
 "The app state (the snapshot)",
 "The app logs (the structured)",
 "The app errors (the typed)",
 "The app crash (the dialog)",
 "The app watchdog (the hang)",
 "The app priority (the foreground)",
 "The app energy (the budget)",
 "The app telemetry (the consent)",
 "The app docs (the generated)",
 "The app test (the smoke)",
 "The app bench (the launch)",
 "The app fuzz (the inputs)",
 "The Colonel as the app core (the HolyC)",
 "The Colonel as the OS core (the ring-0)",
 "The Colonel as the shell core (the UI)",
 "The Colonel as the loader core (the .wubu)",
 "The Colonel as the AGI core (the eval)",
 "The Colonel as the verifier core (the attest)",
 "The Colonel as the console core (the REPL)",
 "The Colonel as the IDE core (the editor)",
 "The Colonel as the debugger core (the breaks)",
 "The Colonel as the scheduler core (the tasks)",
 "The Colonel as the memory core (the GC)",
 "The Colonel as the IPC core (the messages)",
 "The Colonel as the render core (the HolyC UI)",
 "The Colonel as the theme core (the HolyC themes)",
 "The Colonel as the sound core (the HolyC synth)",
 "The Colonel as the AI core (the HolyC models)",
 "The Colonel as the network core (the HolyC 9P)",
 "The Colonel as the storage core (the HolyC FS)",
 "The Colonel as the security core (the HolyC MAC)",
 "The Colonel as the test core (the HolyC asserts)",
 "The Colonel as the bench core (the HolyC perf)",
 "The Colonel as the fuzz core (the HolyC mutation)",
 "The Colonel as the docs core (the HolyC help)",
 "The Colonel as the upgrade core (the HolyC patches)",
 "The Colonel as the module core (the HolyC modules)",
 "The HolyC module system (the .HC files)",
 "The HolyC #include (the header)",
 "The HolyC symbol table (the export)",
 "The HolyC FFI (the C calls)",
 "The HolyC FFI (the syscalls)",
 "The HolyC FFI (the 9P)",
 "The HolyC FFI (the Vulkan)",
 "The HolyC FFI (the CUDA)",
 "The HolyC FFI (the audio)",
 "The HolyC FFI (the GUI)",
 "The HolyC FFI (the kernel)",
 "The HolyC REPL (the persistent)",
 "The HolyC debugger (the breakpoints)",
 "The HolyC watch (the variables)",
 "The HolyC stack (the trace)",
 "The HolyC step (the single)",
 "The HolyC inspect (the memory)",
 "The HolyC disasm (the x86-64)",
 "The HolyC profiles (the perf)",
 "The HolyC compile (the AOT)",
 "The HolyC JIT (the eval)",
 "The HolyC PTX (the GPU)",
 "The HolyC docs (the ZealOS parity)",
 "The HolyC tests (the suite)",
 "The HolyC fuzz (the parser)",
 "The HolyC bench (the eval/sec)",
 "The module graph (the deps view)",
 "The module health (the CI)",
 "The module publish (the registry)",
 "The module install (the 9P pull)",
 "The module rollback (the previous)",
 "The module quarantine (the bad)",
 "The module signing (the verify)",
 "The module update (the delta)",
 "The module cache (the compiled)",
 "The module warm (the preload)",
 "The module cold (the lazy)",
 "The module swap (the hot)",
 "The module dead (the collect)",
 "The module stats (the size)",
 "The module energy (the per-module)",
 "The module audit (the provenance)",
 "The module standard (the template)",
 "The module docs (the generator)",
 "The module test (the per-module)",
 "The module bench (the per-module)",
 "The module fuzz (the per-module)",
 "The module roadmap (this bank)",
], "The module discipline (opaque structs, no monoliths) -> everything through the HolyC Colonel")

theme("GU-I", "The polish & motion", [
 "The XP Luna vibes (the blue gradient)",
 "The Win98 vibes (the silver bevel)",
 "The theme transitions (the crossfade)",
 "The window open animation (the grow)",
 "The window close animation (the shrink)",
 "The minimize animation (to the taskbar)",
 "The maximize animation (the expand)",
 "The restore animation (the shrink back)",
 "The menu fade (the 80ms)",
 "The menu slide (the 120ms)",
 "The tooltip fade (the 200ms)",
 "The tooltip delay (the 500ms)",
 "The button pulse (the hover)",
 "The button click (the press)",
 "The icon bounce (the launch)",
 "The taskbar glow (the hover)",
 "The tray pop (the notify)",
 "The notification slide (the panel)",
 "The notification fade (the dismiss)",
 "The search expand (the start menu)",
 "The cursor blink (the text)",
 "The selection fade (the plate)",
 "The wallpaper crossfade (the slideshow)",
 "The boot sequence (the logo + the chime)",
 "The login sequence (the theme)",
 "The shutdown sequence (the chord)",
 "The splash screen (the fast)",
 "The first-run tour (the arrows)",
 "The hover states (the every-control)",
 "The pressed states (the every-control)",
 "The disabled states (the dim)",
 "The focus states (the ring)",
 "The scroll momentum (the wheel)",
 "The touch feedback (the ripple)",
 "The drag feedback (the ghost)",
 "The drop feedback (the highlight)",
 "The snap feedback (the outline)",
 "The resize feedback (the live)",
 "The move feedback (the live)",
 "The progress shimmer (the XP bar)",
 "The busy cursor (the spinner)",
 "The wait cursor (the hourglass)",
 "The error shake (the dialog)",
 "The success pop (the toast)",
 "The warning pulse (the badge)",
 "The sounds (the event scheme)",
 "The sound volume (the per-event)",
 "The sound themes (the Win98/XP)",
 "The sound preview (the applet)",
 "The haptics (the touch)",
 "The accessibility motion (the reduced)",
 "The color transitions (the theme)",
 "The font transitions (the DPI)",
 "The layout transitions (the resize)",
 "The adaptive layout (the window size)",
 "The responsive panels (the collapse)",
 "The overview zoom (the expose)",
 "The peek blur (the preview)",
 "The transparency (the acrylic-ish)",
 "The rounded corners (the theme)",
 "The shadows (the depth)",
 "The elevation (the z-depth)",
 "The light mode (the theme)",
 "The dark mode (the theme)",
 "The auto mode (the time)",
 "The OLED mode (the pure black)",
 "The paper mode (the reading)",
 "The sepia mode (the comfort)",
 "The contrast mode (the high)",
 "The color-blind mode (the palette)",
 "The night mode (the blue cut)",
 "The animation timings (the spec)",
 "The easing curves (the spec)",
 "The motion budget (the fps guard)",
 "The motion energy (the IJ ledger)",
 "The motion test (the frame asserts)",
 "The motion bench (the 60fps)",
 "The motion fuzz (the params)",
 "The startup chime (the synthesized)",
 "The shutdown chord (the synthesized)",
 "The notification chime (the synthesized)",
 "The error sound (the synthesized)",
 "The click sound (the synthesized)",
 "The maximize blip (the synthesized)",
 "The minimize blip (the synthesized)",
 "The restore blip (the synthesized)",
 "The Bonzi sounds (the moods)",
 "The AGI sounds (the promotions)",
 "The achievement fanfare (the closing)",
 "The level-up sound (the milestones)",
 "The ambient music (the mood-reactive)",
 "The typing sound (the optional)",
 "The completion sound (the tasks)",
 "The morning sound (the wake)",
 "The evening sound (the wind-down)",
 "The holiday themes (the seasonal)",
 "The pride themes (the flags)",
 "The user themes (the custom)",
 "The theme gallery (the browse)",
 "The theme share (the export)",
 "The theme store (the future)",
 "The polish audit (the consistency)",
 "The polish test (the visual suite)",
 "The polish docs (the style guide)",
], "The XP/98 vibes -> the motion spec -> the synthesized sound scheme -> the Bonzi moods, all theme-driven")

theme("GU-J", "The cross-OS loading (all the OSes through the Colonel)", [
 "The .wubu universal format (the dispatch)",
 "The ELF loader (the native)",
 "The PE loader (the Windows)",
 "The Mach-O loader (the macOS)",
 "The WASM loader (the web)",
 "The HolyC source loader (the eval)",
 "The C source loader (the compile)",
 "The Python loader (the script)",
 "The Node loader (the script)",
 "The shell script loader",
 "The batch loader (the DOS)",
 "The DOS EXE loader (the 8086 emu)",
 "The COM loader (the 8086)",
 "The NES loader (the rom)",
 "The GB loader (the rom)",
 "The SNES loader (the future)",
 "The Amiga loader (the future)",
 "The Atari loader (the future)",
 "The C64 loader (the future)",
 "The ZX Spectrum loader (the future)",
 "The DOSBox integration (the DOS)",
 "The Wine integration (the Win32)",
 "The Proton integration (the Steam)",
 "The GameScope integration (the fullscreen)",
 "The DXVK integration (the DX9-11)",
 "The VKD3D integration (the DX12)",
 "The WineVulkan (the DX-vulkan)",
 "The native Linux (the ELF)",
 "The flatpak (the bundles)",
 "The snap (the bundles)",
 "The AppImage (the bundles)",
 "The OCI containers (the pods)",
 "The Arch packages (the pacman)",
 "The AUR (the community)",
 "The Steam Runtime (the soldier)",
 "The 9P remote (the network OS)",
 "The SSH (the remote shell)",
 "The VNC (the remote desktop)",
 "The RDP (the future)",
 "The Wayland clients (the native)",
 "The X11 clients (the XWayland-ish)",
 "The VSL (the NT syscall bridge)",
 "The 297 NT syscalls (the mapping)",
 "The win32k (the GUI syscalls)",
 "The kernel-mode (the drivers)",
 "The user-mode (the apps)",
 "The 8086 emulation (the in-process)",
 "The x86-64 native (the JIT)",
 "The ARM (the future)",
 "The RISC-V (the future)",
 "The GPU shaders (the SPIR-V)",
 "The Metal kernels (the AVF)",
 "The CUDA kernels (the PTX)",
 "The Vulkan pipelines (the compute)",
 "The HolyC as the loader (the Colonel eval)",
 "The HolyC as the runtime (the host effects)",
 "The HolyC as the bridge (the FFI)",
 "The loader magic detection (the bytes)",
 "The loader security (the verify)",
 "The loader sandbox (the seccomp)",
 "The loader energy (the budget)",
 "The loader telemetry (the launches)",
 "The loader tests (the each-format)",
 "The loader fuzz (the garbage bytes)",
 "The loader bench (the launch ms)",
 "The cross-OS GUI (the Win98 shell for all)",
 "The cross-OS themes (the unified)",
 "The cross-OS clipboard (the bridge)",
 "The cross-OS drag-drop (the bridge)",
 "The cross-OS files (the 9P mount)",
 "The cross-OS sound (the bridge)",
 "The cross-OS MIDI (the future)",
 "The cross-OS GPU (the unified)",
 "The cross-OS networking (the bridge)",
 "The cross-OS printing (the future)",
 "The cross-OS devices (the 9P /dev)",
 "The cross-OS time (the sync)",
 "The cross-OS users (the mapping)",
 "The cross-OS permissions (the grants)",
 "The cross-OS data (the migration)",
 "The cross-OS backup (the snapshot)",
 "The cross-OS restore (the rollback)",
 "The cross-OS update (the delta)",
 "The cross-OS quarantine (the bad)",
 "The cross-OS attest (the verifier)",
 "The cross-OS ledger (the provenance)",
 "The cross-OS audit (the EDR)",
 "The cross-OS support (the docs)",
 "The cross-OS tests (the matrix)",
 "The cross-OS bench (the compare)",
 "The Colonel manifest (the everything via HolyC)",
 "The Colonel dispatch (the loader routing)",
 "The Colonel sandbox (the HolyC-isolated)",
 "The Colonel verifier (the attest-gated)",
 "The Colonel ABI (the stable)",
 "The Colonel versioning (the semver)",
 "The Colonel registry (the modules)",
 "The Colonel compiler (the AOT)",
 "The Colonel interpreter (the REPL)",
 "The Colonel kernel (the ring-0)",
 "The Colonel user (the ring-3)",
 "The Colonel the OS (the TempleOS vision)",
 "The Colonel the everything (the final form)",
 "The cross-OS roadmap (this bank)",
], "The .wubu magic dispatch -> the PE/ELF/Mach-O/WASM/DOS loaders -> the VSL NT bridge -> ALL through the HolyC Colonel")

with open("docs/compendium/04-roadmap/gui-gap-index.md", "w") as f:
    f.write("# GUI Gap Index -- 1000 goals + gaps\n\n")
    f.write("Date: 2026-08-02. The 'best most modular AI-powered OS ever' GUI\n")
    f.write("register, plus the cross-OS loading vision. EVERYTHING flows through\n")
    f.write("the HolyC Colonel (the TempleOS/ZealOS lineage): apps, OS code, and\n")
    f.write("cross-OS payloads dispatch through the Colonel. Status: `open` =\n")
    f.write("not yet built; `wired` = implemented + tested.\n")
    f.write("".join(T))
print("gui bank written")
